<?php
/**
 * Список доменов одноразовых / временных почт (disposable email).
 * Регистрация с таких адресов блокируется (см. is_disposable_email в db.php).
 *
 * Проверка учитывает поддомены: foo.mailinator.com тоже попадёт под mailinator.com.
 * Список можно дополнять — просто добавь домен в нижнем регистре.
 */
return [
    '0-mail.com', '027168.com', '0815.ru', '0clickemail.com', '0wnd.net', '0wnd.org',
    '10mail.com', '10mail.org', '10minutemail.com', '10minutemail.net', '10minutemail.co.uk',
    '10minutemail.de', '10minutemail.ru', '20minutemail.com', '20mail.it', '20email.eu',
    '2prong.com', '30minutemail.com', '33mail.com', '3d-painting.com', '3dxtras.com',
    '4warding.com', '4warding.net', '4warding.org', '60minutemail.com', '675hosting.com',
    '6paq.com', '7days-printing.com', '7tags.com', '99experts.com', '9ox.net',
    'a-bc.net', 'afrobacon.com', 'ajaxapp.net', 'amilegit.com', 'amiri.net',
    'anonbox.net', 'anonmails.de', 'anonymbox.com', 'antichef.com', 'antichef.net',
    'antispam.de', 'armyspy.com', 'azmeil.tk', 'baxomale.ht.cx', 'beefmilk.com',
    'binkmail.com', 'bio-muesli.net', 'bobmail.info', 'bodhi.lawlita.com', 'bofthew.com',
    'brefmail.com', 'broadbandninja.com', 'bsnow.net', 'bugmenot.com', 'bumpymail.com',
    'bund.us', 'burnthespam.info', 'buyusedlibrarybooks.org', 'byom.de',
    'c2.hu', 'card.zp.ua', 'casualdx.com', 'cek.pm', 'centermail.com', 'centermail.net',
    'chammy.info', 'childsavetrust.org', 'chogmail.com', 'choicemail1.com', 'clixser.com',
    'cmail.com', 'cmail.net', 'cmail.org', 'consumerriot.com', 'cool.fr.nf', 'correo.blogos.net',
    'cosmorph.com', 'courriel.fr.nf', 'courrieltemporaire.com', 'crapmail.org', 'crazymailing.com',
    'cubiclink.com', 'curryworld.de', 'cust.in', 'cuvox.de',
    'dacoolest.com', 'dandikmail.com', 'dayrep.com', 'dcemail.com', 'deadaddress.com',
    'deadspam.com', 'despam.it', 'devnullmail.com', 'dfgh.net', 'digitalsanctuary.com',
    'discardmail.com', 'discardmail.de', 'disposableaddress.com', 'disposableinbox.com',
    'dispose.it', 'dispostable.com', 'dodgeit.com', 'dodgit.com', 'donemail.ru',
    'dontreg.com', 'dontsendmespam.de', 'drdrb.com', 'drdrb.net', 'dump-email.info',
    'dumpandjunk.com', 'dumpyemail.com', 'duskmail.com',
    'e4ward.com', 'easytrashmail.com', 'einrot.com', 'email60.com', 'emaildienst.de',
    'emailgo.de', 'emailias.com', 'emaillime.com', 'emailmiser.com', 'emailsensei.com',
    'emailtemporanea.com', 'emailtemporanea.net', 'emailtemporar.ro', 'emailtemporario.com.br',
    'emailthe.net', 'emailtmp.com', 'emailwarden.com', 'emailx.at.hm', 'emailxfer.com',
    'emeil.in', 'emeil.ir', 'emkei.cz', 'emz.net', 'enterto.com', 'ephemail.net',
    'etranquil.com', 'etranquil.net', 'etranquil.org', 'evopo.com', 'explodemail.com',
    'fakeinbox.com', 'fakeinformation.com', 'fakemail.fr', 'fakemailgenerator.com',
    'fansworldwide.de', 'fastacura.com', 'fastchevy.com', 'fastchrysler.com', 'fastkawasaki.com',
    'fastmazda.com', 'fastmitsubishi.com', 'fastnissan.com', 'fastsubaru.com', 'fastsuzuki.com',
    'fasttoyota.com', 'fastyamaha.com', 'fightallspam.com', 'filzmail.com', 'fizmail.com',
    'fleckens.hu', 'frapmail.com', 'friendlymail.co.uk', 'fuckingduh.com', 'fudgerub.com',
    'fyii.de',
    'garliclife.com', 'gehensiemirnichtaufdensack.de', 'get1mail.com', 'get2mail.fr',
    'getairmail.com', 'getmails.eu', 'getonemail.com', 'getonemail.net', 'ghosttexter.de',
    'girlsundertheinfluence.com', 'gishpuppy.com', 'gmial.com', 'goemailgo.com', 'gotmail.net',
    'gotmail.org', 'gotti.otherinbox.com', 'great-host.in', 'greensloth.com', 'grr.la',
    'guerillamail.biz', 'guerillamail.com', 'guerrillamail.biz', 'guerrillamail.com',
    'guerrillamail.de', 'guerrillamail.net', 'guerrillamail.org', 'guerrillamailblock.com',
    'gustr.com',
    'h.mintemail.com', 'haltospam.com', 'harakirimail.com', 'hatespam.org', 'herp.in',
    'hidemail.de', 'hidzz.com', 'hmamail.com', 'hochsitze.com', 'hotpop.com', 'hulapla.de',
    'ieatspam.eu', 'ieatspam.info', 'ihateyoualot.info', 'iheartspam.org', 'imails.info',
    'inbax.tk', 'inbox.si', 'inboxalias.com', 'inboxclean.com', 'inboxclean.org',
    'incognitomail.com', 'incognitomail.net', 'incognitomail.org', 'insorg-mail.info',
    'instant-mail.de', 'ipoo.org', 'irish2me.com', 'iwi.net',
    'jetable.com', 'jetable.fr.nf', 'jetable.net', 'jetable.org', 'jnxjn.com', 'jourrapide.com',
    'junk1e.com', 'kasmail.com', 'kaspop.com', 'keepmymail.com', 'killmail.com', 'killmail.net',
    'klassmaster.com', 'klzlk.com', 'koszmail.pl', 'kurzepost.de',
    'lackmail.net', 'lawlita.com', 'letthemeatspam.com', 'lhsdv.com', 'lifebyfood.com',
    'link2mail.net', 'litedrop.com', 'lol.ovpn.to', 'lookugly.com', 'lortemail.dk',
    'lr78.com', 'lroid.com', 'lukop.dk', 'm21.cc', 'mail-temporaire.fr', 'mail.by',
    'mail.mezimages.net', 'mail2rss.org', 'mail333.com', 'mailbidon.com', 'mailblocks.com',
    'mailbucket.org', 'mailcatch.com', 'maildrop.cc', 'maileater.com', 'mailexpire.com',
    'mailfa.tk', 'mailforspam.com', 'mailfreeonline.com', 'mailguard.me', 'mailimate.com',
    'mailin8r.com', 'mailinater.com', 'mailinator.com', 'mailinator.net', 'mailinator.org',
    'mailinator2.com', 'mailincubator.com', 'mailme.lv', 'mailme24.com', 'mailmetrash.com',
    'mailmoat.com', 'mailms.com', 'mailnesia.com', 'mailnull.com', 'mailorg.org',
    'mailpick.biz', 'mailrock.biz', 'mailscrap.com', 'mailshell.com', 'mailsiphon.com',
    'mailtemp.info', 'mailtome.de', 'mailtothis.com', 'mailtrash.net', 'mailtv.net',
    'mailtv.tv', 'mailzilla.com', 'mailzilla.org', 'makemetheking.com', 'manybrain.com',
    'mbx.cc', 'mega.zik.dj', 'meinspamschutz.de', 'meltmail.com', 'messagebeamer.de',
    'mezimages.net', 'ministry-of-silly-walks.de', 'mintemail.com', 'misterpinball.de',
    'moakt.com', 'mobi.web.id', 'moburl.com', 'monumentmail.com', 'msa.minsmail.com',
    'mt2009.com', 'mt2014.com', 'mt2015.com', 'mvrht.com', 'mx0.wwwnew.eu', 'mycleaninbox.net',
    'mymail-in.net', 'mypacks.net', 'mypartyclip.de', 'myphantomemail.com', 'mysamp.de',
    'mytempemail.com', 'mytempmail.com', 'mytrashmail.com',
    'nabuma.com', 'neomailbox.com', 'nepwk.com', 'nervmich.net', 'nervtmich.net',
    'netmails.com', 'netmails.net', 'netzidiot.de', 'neverbox.com', 'nice-4u.com',
    'nincsmail.com', 'nincsmail.hu', 'nnh.com', 'no-spam.ws', 'noblepioneer.com',
    'nomail.pw', 'nomail.xl.cx', 'nomail2me.com', 'nomorespamemails.com', 'nospam.ze.tc',
    'nospam4.us', 'nospamfor.us', 'nospammail.net', 'notmailinator.com', 'nowhere.org',
    'nowmymail.com', 'nurfuerspam.de', 'nwldx.com',
    'objectmail.com', 'obobbo.com', 'odaymail.com', 'odnorazovoe.ru', 'one-time.email',
    'oneoffemail.com', 'onewaymail.com', 'onlatedotcom.info', 'online.ms', 'oopi.org',
    'opayq.com', 'ordinaryamerican.net', 'otherinbox.com', 'ovpn.to', 'owlpic.com',
    'pancakemail.com', 'pcusers.otherinbox.com', 'pjjkp.com', 'plexolan.de',
    'politikerclub.de', 'poofy.org', 'pookmail.com', 'privatdemail.net',
    'proxymail.eu', 'prtnx.com', 'putthisinyourspamdatabase.com', 'pwrby.com',
    'quickinbox.com', 'rcpt.at', 'reallymymail.com', 'realtyalerts.ca', 'recode.me',
    'recursor.net', 'reliable-mail.com', 'rhyta.com', 'rmqkr.net', 'royal.net', 'rppkn.com',
    'rtrtr.com', 's0ny.net', 'safe-mail.net', 'safersignup.de', 'safetymail.info',
    'safetypost.de', 'saynotospams.com', 'schafmail.de', 'schrott-email.de', 'secretemail.de',
    'secure-mail.biz', 'selfdestructingmail.com', 'sendspamhere.com', 'sharklasers.com',
    'shieldemail.com', 'shiftmail.com', 'shitmail.me', 'shitmail.org', 'shitware.nl',
    'shmeriously.com', 'shortmail.net', 'sibmail.com', 'sinnlos-mail.de', 'slapsfromlastnight.com',
    'slaskpost.se', 'smashmail.de', 'smellfear.com', 'snakemail.com', 'sneakemail.com',
    'snkmail.com', 'sofimail.com', 'sofort-mail.de', 'sogetthis.com', 'soodonims.com',
    'spam.la', 'spam.su', 'spam4.me', 'spamavert.com', 'spambob.com', 'spambob.net',
    'spambob.org', 'spambog.com', 'spambog.de', 'spambog.net', 'spambog.ru', 'spambox.us',
    'spamcannon.com', 'spamcannon.net', 'spamcero.com', 'spamcon.org', 'spamcorptastic.com',
    'spamcowboy.com', 'spamcowboy.net', 'spamcowboy.org', 'spamday.com', 'spamex.com',
    'spamfree.eu', 'spamfree24.com', 'spamfree24.de', 'spamfree24.org', 'spamgoes.in',
    'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org', 'spamherelots.com',
    'spamhereplease.com', 'spamhole.com', 'spamify.com', 'spaml.com', 'spaml.de',
    'spammotel.com', 'spamobox.com', 'spamslicer.com', 'spamspot.com', 'spamthis.co.uk',
    'spamtroll.net', 'speed.1s.fr', 'spoofmail.de', 'squizzy.de', 'ssoia.com',
    'startkeys.com', 'stinkefinger.net', 'stop-my-spam.com', 'stuffmail.de', 'super-auswahl.de',
    'supergreatmail.com', 'supermailer.jp', 'superrito.com', 'superstachel.de', 'suremail.info',
    'talkinator.com', 'teewars.org', 'teleworm.com', 'teleworm.us', 'temp-mail.com',
    'temp-mail.de', 'temp-mail.org', 'temp-mail.ru', 'tempail.com', 'tempalias.com',
    'tempe-mail.com', 'tempemail.biz', 'tempemail.com', 'tempemail.net', 'tempinbox.co.uk',
    'tempinbox.com', 'tempmail.eu', 'tempmail.it', 'tempmail2.com', 'tempmaildemo.com',
    'tempmailer.com', 'tempmailer.de', 'tempomail.fr', 'temporarily.de', 'temporarioemail.com.br',
    'temporaryemail.net', 'temporaryforwarding.com', 'temporaryinbox.com', 'temporarymailaddress.com',
    'tempthe.net', 'thanksnospam.info', 'thankyou2010.com', 'thc.st', 'thelimestones.com',
    'thisisnotmyrealemail.com', 'thismail.net', 'throwam.com', 'throwawayemailaddress.com',
    'tilien.com', 'tittbit.in', 'tizi.com', 'tmail.ws', 'tmailinator.com', 'toiea.com',
    'toomail.biz', 'topranklist.de', 'tradermail.info', 'trash-mail.at', 'trash-mail.com',
    'trash-mail.de', 'trash2009.com', 'trashdevil.com', 'trashemail.de', 'trashmail.at',
    'trashmail.com', 'trashmail.de', 'trashmail.me', 'trashmail.net', 'trashmail.org',
    'trashmail.ws', 'trashmailer.com', 'trashymail.com', 'trashymail.net', 'trbvm.com',
    'trialmail.de', 'trillianpro.com', 'tryalert.com', 'turual.com', 'twinmail.de',
    'tyldd.com', 'uggsrock.com', 'umail.net', 'upliftnow.com', 'uplipht.com', 'uroid.com',
    'us.af', 'venompen.com', 'veryrealemail.com', 'vidchart.com', 'viditag.com', 'viralplays.com',
    'vpn.st', 'vsimcard.com', 'vubby.com', 'wasteland.rfc822.org', 'webemail.me', 'weg-werf-email.de',
    'wegwerf-emails.de', 'wegwerfadresse.de', 'wegwerfemail.com', 'wegwerfemail.de',
    'wegwerfmail.de', 'wegwerfmail.info', 'wegwerfmail.net', 'wegwerfmail.org', 'wetrainbayarea.com',
    'wetrainbayarea.org', 'wh4f.org', 'whyspam.me', 'willhackforfood.biz', 'willselfdestruct.com',
    'winemaven.info', 'wronghead.com', 'wuzup.net', 'wuzupmail.net', 'www.e4ward.com',
    'www.mailinator.com', 'wwwnew.eu', 'x.ip6.li', 'xagloo.com', 'xemaps.com', 'xents.com',
    'xmaily.com', 'xoxy.net', 'yapped.net', 'yep.it', 'yogamaven.com',
    'yopmail.com', 'yopmail.fr', 'yopmail.net', 'yourdomain.com', 'ypmail.webarnak.fr.eu.org',
    'yuurok.com', 'z1p.biz', 'za.com', 'zehnminuten.de', 'zehnminutenmail.de', 'zippymail.info',
    'zoaxe.com', 'zoemail.com', 'zoemail.net', 'zoemail.org', 'zomg.info', 'zxcv.com',
    'zxcvbnm.com', 'zzz.com',
];
