<?php

function ensure_gso_schema($pdo) {
    $pdo->exec("CREATE TABLE IF NOT EXISTS gso_proposals (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        author_account_id BIGINT NOT NULL,
        title VARCHAR(180) NOT NULL,
        description TEXT NOT NULL,
        expected_result TEXT NOT NULL,
        status VARCHAR(32) NOT NULL DEFAULT 'voting',
        eligible_voters INTEGER NOT NULL DEFAULT 1,
        quorum_required INTEGER NOT NULL DEFAULT 1,
        voting_duration_days SMALLINT NOT NULL DEFAULT 3,
        voting_ends_at TIMESTAMP NOT NULL,
        vote_closed_at TIMESTAMP NULL,
        vote_result VARCHAR(16) NULL,
        vote_round INTEGER NOT NULL DEFAULT 1,
        head_rejection_count SMALLINT NOT NULL DEFAULT 0,
        head_account_id BIGINT NULL,
        head_decision VARCHAR(16) NULL,
        head_note TEXT NULL,
        head_decided_at TIMESTAMP NULL,
        implementation_status VARCHAR(20) NOT NULL DEFAULT 'none',
        implementation_note TEXT NULL,
        implemented_by BIGINT NULL,
        implemented_at TIMESTAMP NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)
    )");
    $pdo->exec("CREATE INDEX IF NOT EXISTS idx_gso_proposals_status ON gso_proposals (status, created_at)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS idx_gso_proposals_author ON gso_proposals (author_account_id)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS idx_gso_proposals_vote_end ON gso_proposals (status, voting_ends_at)");
    $pdo->exec("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_gso_proposals_updated_at') THEN CREATE TRIGGER trg_gso_proposals_updated_at BEFORE UPDATE ON gso_proposals FOR EACH ROW EXECUTE FUNCTION update_updated_at_column(); END IF; END $$");

    $pdo->exec("CREATE TABLE IF NOT EXISTS gso_votes (
        proposal_id BIGINT NOT NULL,
        vote_round INTEGER NOT NULL DEFAULT 1,
        account_id BIGINT NOT NULL,
        choice VARCHAR(12) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (proposal_id, vote_round, account_id)
    )");
    $pdo->exec("CREATE INDEX IF NOT EXISTS idx_gso_votes_account ON gso_votes (account_id, updated_at)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS idx_gso_votes_choice ON gso_votes (proposal_id, vote_round, choice)");
    $pdo->exec("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_gso_votes_updated_at') THEN CREATE TRIGGER trg_gso_votes_updated_at BEFORE UPDATE ON gso_votes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column(); END IF; END $$");

    $pdo->exec("CREATE TABLE IF NOT EXISTS gso_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        proposal_id BIGINT NOT NULL,
        actor_account_id BIGINT NULL,
        event_type VARCHAR(32) NOT NULL,
        detail VARCHAR(255) NOT NULL DEFAULT '',
        metadata_json TEXT NULL,
        visibility VARCHAR(16) NOT NULL DEFAULT 'public',
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)
    )");
    $pdo->exec("CREATE INDEX IF NOT EXISTS idx_gso_events_proposal ON gso_events (proposal_id, created_at)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS idx_gso_events_actor ON gso_events (actor_account_id, created_at)");

    if (!db_column_exists($pdo, 'gso_proposals', 'voting_duration_days')) {
        $pdo->exec("ALTER TABLE gso_proposals ADD COLUMN voting_duration_days SMALLINT NOT NULL DEFAULT 3");
    }
    if (!db_column_exists($pdo, 'gso_proposals', 'vote_round')) {
        $pdo->exec("ALTER TABLE gso_proposals ADD COLUMN vote_round INTEGER NOT NULL DEFAULT 1");
    }
    if (!db_column_exists($pdo, 'gso_proposals', 'head_rejection_count')) {
        $pdo->exec("ALTER TABLE gso_proposals ADD COLUMN head_rejection_count SMALLINT NOT NULL DEFAULT 0");
    }
    if (!db_column_exists($pdo, 'gso_events', 'visibility')) {
        $pdo->exec("ALTER TABLE gso_events ADD COLUMN visibility VARCHAR(16) NOT NULL DEFAULT 'public'");
    }
    if (!db_column_exists($pdo, 'gso_votes', 'vote_round')) {
        $pdo->exec("ALTER TABLE gso_votes ADD COLUMN vote_round INTEGER NOT NULL DEFAULT 1");
    }

    // Проверяем состав первичного ключа gso_votes через pg_constraint
    $primary_columns = [];
    $stmt = $pdo->prepare("SELECT a.attname FROM pg_index i JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey) WHERE i.indrelid = 'gso_votes'::regclass AND i.indisprimary ORDER BY array_position(i.indkey, a.attnum)");
    $stmt->execute();
    foreach ($stmt->fetchAll() as $row) {
        $primary_columns[] = $row['attname'];
    }
    if ($primary_columns !== ['proposal_id', 'vote_round', 'account_id']) {
        $pdo->exec("ALTER TABLE gso_votes DROP CONSTRAINT IF EXISTS gso_votes_pkey");
        $pdo->exec("ALTER TABLE gso_votes ADD PRIMARY KEY (proposal_id, vote_round, account_id)");
    }
    $has_round_choice_index = false;
    $idx_stmt = $pdo->prepare("SELECT 1 FROM pg_indexes WHERE indexname = 'idx_gso_votes_round_choice'");
    $idx_stmt->execute();
    $has_round_choice_index = $idx_stmt->fetch() !== false;
    if (!$has_round_choice_index) {
        $pdo->exec("CREATE INDEX idx_gso_votes_round_choice ON gso_votes (proposal_id, vote_round, choice)");
    }
}

function gso_locale(): string
{
    $lang = function_exists('current_lang') ? current_lang() : 'ru';
    return in_array($lang, ['ru', 'uk', 'en'], true) ? $lang : 'ru';
}

function gso_localize_error($message, $lang = null): string
{
    $message = (string)$message;
    $lang = $lang === null ? gso_locale() : $lang;
    $lang = in_array($lang, ['ru', 'uk', 'en'], true) ? $lang : 'ru';
    if ($lang === 'ru') {
        return $message;
    }
    $translations = [
        'uk' => [
            'Только члены команды могут подавать предложения.' => 'Лише члени команди можуть подавати пропозиції.',
            'Название предложения должно содержать от 8 до 180 символов.' => 'Назва пропозиції має містити від 8 до 180 символів.',
            'Описание предложения должно содержать от 30 до 10 000 символов.' => 'Опис пропозиції має містити від 30 до 10 000 символів.',
            'Опишите ожидаемый результат минимум в 10 символах.' => 'Опишіть очікуваний результат щонайменше у 10 символах.',
            'Досрочно завершить голосование может только глава проекта или глава совета.' => 'Достроково завершити голосування може лише глава проєкту або голова ради.',
            'Нельзя завершить голосование до достижения кворума.' => 'Не можна завершити голосування до досягнення кворуму.',
            'Обычные игроки не могут голосовать.' => 'Звичайні гравці не можуть голосувати.',
            'Выберите допустимый вариант голосования.' => 'Оберіть допустимий варіант голосування.',
            'Голосование уже завершено.' => 'Голосування вже завершено.',
            'Выберите решение главы совета.' => 'Оберіть рішення голови ради.',
            'Это решение может принять только глава проекта или глава совета.' => 'Це рішення може прийняти лише глава проєкту або голова ради.',
            'Добавьте краткое обоснование решения.' => 'Додайте коротке обґрунтування рішення.',
            'Предложение ещё не передано главе совета или уже обработано.' => 'Пропозицію ще не передано голові ради або її вже опрацьовано.',
            'Реализацией решений может управлять только глава проекта.' => 'Керувати реалізацією рішень може лише глава проєкту.',
            'Неизвестное действие реализации.' => 'Невідома дія реалізації.',
            'Опишите, как решение было реализовано.' => 'Опишіть, як було реалізовано рішення.',
            'Это решение не находится в очереди реализации.' => 'Це рішення не перебуває в черзі реалізації.',
            'Менять статус принятого решения может только глава проекта.' => 'Змінювати статус прийнятого рішення може лише глава проєкту.',
            'Неизвестный статус решения.' => 'Невідомий статус рішення.',
            'Опишите причину смены статуса решения минимум в 5 символах.' => 'Опишіть причину зміни статусу рішення щонайменше у 5 символах.',
            'Решение ГСО не найдено.' => 'Рішення ГСО не знайдено.',
            'Решение уже находится в этом статусе.' => 'Рішення вже перебуває в цьому статусі.',
        ],
        'en' => [
            'Только члены команды могут подавать предложения.' => 'Only team members can submit proposals.',
            'Название предложения должно содержать от 8 до 180 символов.' => 'The proposal title must contain between 8 and 180 characters.',
            'Описание предложения должно содержать от 30 до 10 000 символов.' => 'The proposal description must contain between 30 and 10,000 characters.',
            'Опишите ожидаемый результат минимум в 10 символах.' => 'Describe the expected result in at least 10 characters.',
            'Досрочно завершить голосование может только глава проекта или глава совета.' => 'Only the project lead or council head can close a vote early.',
            'Нельзя завершить голосование до достижения кворума.' => 'A vote cannot be closed before quorum is reached.',
            'Обычные игроки не могут голосовать.' => 'Regular players cannot vote.',
            'Выберите допустимый вариант голосования.' => 'Choose a valid voting option.',
            'Голосование уже завершено.' => 'The vote has already ended.',
            'Выберите решение главы совета.' => 'Choose the council-head decision.',
            'Это решение может принять только глава проекта или глава совета.' => 'Only the project lead or council head can make this decision.',
            'Добавьте краткое обоснование решения.' => 'Add a brief justification for the decision.',
            'Предложение ещё не передано главе совета или уже обработано.' => 'The proposal has not reached the council head or was already processed.',
            'Реализацией решений может управлять только глава проекта.' => 'Only the project lead can manage implementation.',
            'Неизвестное действие реализации.' => 'Unknown implementation action.',
            'Опишите, как решение было реализовано.' => 'Describe how the decision was implemented.',
            'Это решение не находится в очереди реализации.' => 'This decision is not in the implementation queue.',
            'Менять статус принятого решения может только глава проекта.' => 'Only the project lead can change the status of an approved decision.',
            'Неизвестный статус решения.' => 'Unknown decision status.',
            'Опишите причину смены статуса решения минимум в 5 символах.' => 'Describe the reason for changing the decision status in at least 5 characters.',
            'Решение ГСО не найдено.' => 'GSO decision not found.',
            'Решение уже находится в этом статусе.' => 'The decision is already in this status.',
        ],
    ];
    return $translations[$lang][$message] ?? $message;
}

function gso_can_participate($access) {
    return staff_access_has($access, 'council.participate');
}

function gso_text_length($value) {
    return function_exists('mb_strlen') ? mb_strlen((string)$value, 'UTF-8') : strlen((string)$value);
}

function gso_is_council_head($access) {
    return is_array($access) && ($access['role'] ?? '') === 'orion_council_head';
}

// Глава проекта — создатель сайта, принимает решения совета наравне с главой совета
function gso_is_project_head($access) {
    return is_array($access) && ($access['role'] ?? '') === 'admin';
}

function gso_can_decide_review($access) {
    return gso_is_council_head($access) || gso_is_project_head($access);
}

// Подпись автора решения: глава проекта или глава совета
function gso_decision_authority_label($access) {
    return gso_is_project_head($access) ? 'Глава проекта' : 'Глава совета';
}

function gso_eligible_members($pdo) {
    $stmt = $pdo->query("SELECT a.id, a.username, a.is_admin, a.staff_role, a.last_login, dl.discord_username
        FROM accounts AS a
        LEFT JOIN account_discord_links AS dl ON dl.account_id = a.id
        WHERE a.is_admin = 1 OR a.staff_role IN ('orion_council_head','developer','senior_moderator','moderator','content_maker')
        ORDER BY a.is_admin DESC, CASE a.staff_role WHEN 'developer' THEN 1 WHEN 'orion_council_head' THEN 2 WHEN 'senior_moderator' THEN 3 WHEN 'moderator' THEN 4 WHEN 'content_maker' THEN 5 ELSE 6 END, a.username ASC");
    $members = [];
    foreach ($stmt->fetchAll() as $account) {
        $access = staff_access_for_account($pdo, intval($account['id']));
        if (!$access || !gso_can_participate($access)) {
            continue;
        }
        $account['access'] = $access;
        $members[] = $account;
    }
    return $members;
}

function gso_quorum_required($eligible_voters) {
    $eligible_voters = max(1, intval($eligible_voters));
    if ($eligible_voters === 1) {
        return 1;
    }
    return min($eligible_voters, max(2, intval(ceil($eligible_voters / 2))));
}

function gso_vote_result($yes, $no, $abstain, $quorum) {
    $yes = max(0, intval($yes));
    $no = max(0, intval($no));
    $abstain = max(0, intval($abstain));
    $quorum = max(1, intval($quorum));
    return ($yes + $no + $abstain) >= $quorum && $yes > $no ? 'passed' : 'rejected';
}

// $visibility: 'public' — попадает в публичную хронологию, 'internal' — только для админ-панели
function gso_log_event($pdo, $proposal_id, $event_type, $detail = '', $metadata = [], $actor_id = null, $visibility = 'public') {
    if ($actor_id === null) {
        $actor_id = intval($_SESSION['user_id'] ?? 0) ?: null;
    }
    $visibility = $visibility === 'internal' ? 'internal' : 'public';
    $stmt = $pdo->prepare("INSERT INTO gso_events (proposal_id, actor_account_id, event_type, detail, metadata_json, visibility, created_at) VALUES (?, ?, ?, ?, ?, ?, NOW())");
    $stmt->execute([
        intval($proposal_id),
        $actor_id,
        substr((string)$event_type, 0, 32),
        substr((string)$detail, 0, 255),
        empty($metadata) ? null : json_encode($metadata, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
        $visibility,
    ]);
}

function gso_create_proposal($pdo, $author_id, $title, $description, $expected_result, $duration_days) {
    $author_access = staff_access_for_account($pdo, intval($author_id));
    if (!gso_can_participate($author_access)) {
        throw new RuntimeException('Только члены команды могут подавать предложения.');
    }
    $title = trim((string)$title);
    $description = trim((string)$description);
    $expected_result = trim((string)$expected_result);
    $duration_days = intval($duration_days);
    if (gso_text_length($title) < 8 || gso_text_length($title) > 180) {
        throw new RuntimeException('Название предложения должно содержать от 8 до 180 символов.');
    }
    if (gso_text_length($description) < 30 || gso_text_length($description) > 10000) {
        throw new RuntimeException('Описание предложения должно содержать от 30 до 10 000 символов.');
    }
    if (gso_text_length($expected_result) < 10 || gso_text_length($expected_result) > 4000) {
        throw new RuntimeException('Опишите ожидаемый результат минимум в 10 символах.');
    }
    if (!in_array($duration_days, [1, 3, 7], true)) {
        $duration_days = 3;
    }

    $members = gso_eligible_members($pdo);
    $eligible = max(1, count($members));
    $quorum = gso_quorum_required($eligible);
    $ends_at = $pdo->query("SELECT NOW() + INTERVAL '" . $duration_days . " days'")->fetchColumn();
    $stmt = $pdo->prepare("INSERT INTO gso_proposals (author_account_id, title, description, expected_result, status, eligible_voters, quorum_required, voting_duration_days, voting_ends_at, vote_round, head_rejection_count, implementation_status, created_at, updated_at) VALUES (?, ?, ?, ?, 'voting', ?, ?, ?, ?, 1, 0, 'none', NOW(), NOW())");
    $stmt->execute([$author_id, $title, $description, $expected_result, $eligible, $quorum, $duration_days, $ends_at]);
    $proposal_id = intval($pdo->lastInsertId());
    gso_log_event($pdo, $proposal_id, 'proposal_created', 'Предложение вынесено на голосование.', [
        'eligible_voters' => $eligible,
        'quorum_required' => $quorum,
        'voting_ends_at' => $ends_at,
        'vote_round' => 1,
    ], $author_id);
    return $proposal_id;
}

function gso_finalize_vote($pdo, $proposal_id, $actor_id = null, $allow_early = false) {
    if ($allow_early) {
        $actor_access = staff_access_for_account($pdo, intval($actor_id));
        if (!$actor_access || !in_array($actor_access['role'], ['admin', 'orion_council_head'], true)) {
            throw new RuntimeException('Досрочно завершить голосование может только глава проекта или глава совета.');
        }
    }
    $pdo->beginTransaction();
    try {
        $stmt = $pdo->prepare("SELECT *, (voting_ends_at <= NOW()) AS is_expired FROM gso_proposals WHERE id = ? FOR UPDATE");
        $stmt->execute([intval($proposal_id)]);
        $proposal = $stmt->fetch();
        if (!$proposal || $proposal['status'] !== 'voting') {
            $pdo->commit();
            return false;
        }
        $counts = ['yes' => 0, 'no' => 0, 'abstain' => 0];
        $vote_round = max(1, intval($proposal['vote_round']));
        $stmt = $pdo->prepare("SELECT choice, COUNT(*) AS amount FROM gso_votes WHERE proposal_id = ? AND vote_round = ? GROUP BY choice");
        $stmt->execute([intval($proposal_id), $vote_round]);
        foreach ($stmt->fetchAll() as $row) {
            if (isset($counts[$row['choice']])) {
                $counts[$row['choice']] = intval($row['amount']);
            }
        }
        $cast = array_sum($counts);
        $expired = intval($proposal['is_expired']) === 1;
        $all_voted = $cast >= intval($proposal['eligible_voters']);
        if (!$expired && !$all_voted && !$allow_early) {
            $pdo->commit();
            return false;
        }
        if ($allow_early && $cast < intval($proposal['quorum_required'])) {
            throw new RuntimeException('Нельзя завершить голосование до достижения кворума.');
        }
        $result = gso_vote_result($counts['yes'], $counts['no'], $counts['abstain'], intval($proposal['quorum_required']));
        $next_status = $result === 'passed' ? 'council_review' : 'rejected_vote';
        $stmt = $pdo->prepare("UPDATE gso_proposals SET status = ?, vote_result = ?, vote_closed_at = NOW(), updated_at = NOW() WHERE id = ?");
        $stmt->execute([$next_status, $result, intval($proposal_id)]);
        $detail = 'Тур ' . $vote_round . ' завершён: за ' . $counts['yes'] . ', против ' . $counts['no'] . ', воздержались ' . $counts['abstain'] . '. ';
        $detail .= $result === 'passed' ? 'Решение передано главе совета.' : 'Предложение отклонено голосованием.';
        $event_metadata = $counts;
        $event_metadata['vote_round'] = $vote_round;
        $event_metadata['result'] = $result;
        gso_log_event($pdo, $proposal_id, 'vote_closed', $detail, $event_metadata, $actor_id);
        $pdo->commit();
        return $result;
    } catch (Exception $e) {
        if ($pdo->inTransaction()) {
            $pdo->rollBack();
        }
        throw $e;
    }
}

function gso_sync_expired_votes($pdo) {
    $stmt = $pdo->query("SELECT id FROM gso_proposals WHERE status = 'voting' AND voting_ends_at <= NOW() ORDER BY id ASC");
    foreach ($stmt->fetchAll(PDO::FETCH_COLUMN) as $proposal_id) {
        try {
            gso_finalize_vote($pdo, intval($proposal_id), null, false);
        } catch (Exception $e) {
            error_log('GSO vote synchronization error: ' . $e->getMessage());
        }
    }
}

function gso_cast_vote($pdo, $proposal_id, $account_id, $choice) {
    $voter_access = staff_access_for_account($pdo, intval($account_id));
    if (!gso_can_participate($voter_access)) {
        throw new RuntimeException('Обычные игроки не могут голосовать.');
    }
    $choice = (string)$choice;
    if (!in_array($choice, ['yes', 'no', 'abstain'], true)) {
        throw new RuntimeException('Выберите допустимый вариант голосования.');
    }
    $stmt = $pdo->prepare("SELECT status, eligible_voters, vote_round, (voting_ends_at <= NOW()) AS is_expired FROM gso_proposals WHERE id = ?");
    $stmt->execute([intval($proposal_id)]);
    $proposal = $stmt->fetch();
    if (!$proposal || $proposal['status'] !== 'voting' || intval($proposal['is_expired']) === 1) {
        throw new RuntimeException('Голосование уже завершено.');
    }
    $vote_round = max(1, intval($proposal['vote_round']));
    $stmt = $pdo->prepare("INSERT INTO gso_votes (proposal_id, vote_round, account_id, choice, created_at, updated_at) VALUES (?, ?, ?, ?, NOW(), NOW()) ON CONFLICT (proposal_id, vote_round, account_id) DO UPDATE SET choice = EXCLUDED.choice, updated_at = NOW()");
    $stmt->execute([intval($proposal_id), $vote_round, intval($account_id), $choice]);
    gso_log_event($pdo, $proposal_id, 'vote_cast', 'Голос участника учтён в туре ' . $vote_round . '.', ['choice' => $choice, 'vote_round' => $vote_round], $account_id);

    $stmt = $pdo->prepare("SELECT COUNT(*) FROM gso_votes WHERE proposal_id = ? AND vote_round = ?");
    $stmt->execute([intval($proposal_id), $vote_round]);
    if (intval($stmt->fetchColumn()) >= intval($proposal['eligible_voters'])) {
        gso_finalize_vote($pdo, intval($proposal_id), $account_id, false);
    }
}

function gso_head_decision_transition($decision, $head_rejection_count) {
    $decision = (string)$decision;
    if ($decision === 'accept') {
        return 'implementation';
    }
    if ($decision !== 'reject') {
        throw new RuntimeException('Выберите решение главы совета.');
    }
    return 'rejected_head';
}

function gso_head_decide($pdo, $proposal_id, $head_id, $decision, $note) {
    $head_access = staff_access_for_account($pdo, intval($head_id));
    if (!gso_can_decide_review($head_access)) {
        throw new RuntimeException('Это решение может принять только глава проекта или глава совета.');
    }
    $authority = gso_decision_authority_label($head_access);
    $authority_role = (string)($head_access['role'] ?? '');
    $note = trim((string)$note);
    if (gso_text_length($note) < 5) {
        throw new RuntimeException('Добавьте краткое обоснование решения.');
    }
    $pdo->beginTransaction();
    try {
        $stmt = $pdo->prepare("SELECT * FROM gso_proposals WHERE id = ? FOR UPDATE");
        $stmt->execute([intval($proposal_id)]);
        $proposal = $stmt->fetch();
        if (!$proposal || $proposal['status'] !== 'council_review') {
            throw new RuntimeException('Предложение ещё не передано главе совета или уже обработано.');
        }

        $transition = gso_head_decision_transition($decision, $proposal['head_rejection_count']);
        if ($transition === 'rejected_head') {
            $stmt = $pdo->prepare("UPDATE gso_proposals SET status = 'rejected_head', head_rejection_count = head_rejection_count + 1, head_account_id = ?, head_decision = 'reject', head_note = ?, head_decided_at = NOW(), implementation_status = 'none', updated_at = NOW() WHERE id = ?");
            $stmt->execute([intval($head_id), $note, intval($proposal_id)]);
            gso_log_event(
                $pdo,
                $proposal_id,
                'head_decision',
                $authority . ' отклонил предложение. Решение окончательное, повторного голосования нет. Обоснование: ' . $note,
                ['decision' => 'reject', 'note' => $note, 'vote_round' => intval($proposal['vote_round']), 'authority_role' => $authority_role],
                $head_id
            );
            $pdo->commit();
            return 'rejected_head';
        }

        $stmt = $pdo->prepare("UPDATE gso_proposals SET status = 'implementation', head_account_id = ?, head_decision = 'accept', head_note = ?, head_decided_at = NOW(), implementation_status = 'pending', updated_at = NOW() WHERE id = ?");
        $stmt->execute([intval($head_id), $note, intval($proposal_id)]);
        gso_log_event(
            $pdo,
            $proposal_id,
            'head_decision',
            $authority . ' одобрил решение. Передано на реализацию. Обоснование: ' . $note,
            ['decision' => 'accept', 'note' => $note, 'vote_round' => intval($proposal['vote_round']), 'authority_role' => $authority_role],
            $head_id
        );
        $pdo->commit();
        return 'implementation';
    } catch (Exception $e) {
        if ($pdo->inTransaction()) {
            $pdo->rollBack();
        }
        throw $e;
    }
}

function gso_update_implementation($pdo, $proposal_id, $admin_id, $action, $note) {
    $admin_access = staff_access_for_account($pdo, intval($admin_id));
    if (!$admin_access || ($admin_access['role'] ?? '') !== 'admin') {
        throw new RuntimeException('Реализацией решений может управлять только глава проекта.');
    }
    $states = [
        'start' => ['status' => 'implementation', 'implementation' => 'in_progress', 'event' => 'implementation_started', 'detail' => 'Решение принято в реализацию.'],
        'defer' => ['status' => 'implementation', 'implementation' => 'deferred', 'event' => 'implementation_deferred', 'detail' => 'Реализация решения отложена.'],
        'complete' => ['status' => 'implemented', 'implementation' => 'completed', 'event' => 'implementation_completed', 'detail' => 'Решение реализовано.'],
    ];
    if (!isset($states[$action])) {
        throw new RuntimeException('Неизвестное действие реализации.');
    }
    $note = trim((string)$note);
    if ($action === 'complete' && gso_text_length($note) < 5) {
        throw new RuntimeException('Опишите, как решение было реализовано.');
    }
    $stmt = $pdo->prepare("SELECT status FROM gso_proposals WHERE id = ?");
    $stmt->execute([intval($proposal_id)]);
    if ($stmt->fetchColumn() !== 'implementation') {
        throw new RuntimeException('Это решение не находится в очереди реализации.');
    }
    $state = $states[$action];
    $implemented_at = $action === 'complete' ? $pdo->query("SELECT NOW()")->fetchColumn() : null;
    $stmt = $pdo->prepare("UPDATE gso_proposals SET status = ?, implementation_status = ?, implementation_note = ?, implemented_by = ?, implemented_at = ?, updated_at = NOW() WHERE id = ?");
    $stmt->execute([$state['status'], $state['implementation'], $note, intval($admin_id), $implemented_at, intval($proposal_id)]);
    gso_log_event($pdo, $proposal_id, $state['event'], $state['detail'], ['note' => $note], $admin_id);
}

// Статусы, между которыми глава проекта может переносить уже принятое решение
function gso_status_override_options() {
    return ['voting', 'council_review', 'implementation', 'implemented', 'rejected_vote', 'rejected_head'];
}

function gso_override_status($pdo, $proposal_id, $actor_id, $new_status, $note) {
    $actor_access = staff_access_for_account($pdo, intval($actor_id));
    if (!gso_is_project_head($actor_access)) {
        throw new RuntimeException('Менять статус принятого решения может только глава проекта.');
    }
    $new_status = (string)$new_status;
    if (!in_array($new_status, gso_status_override_options(), true)) {
        throw new RuntimeException('Неизвестный статус решения.');
    }
    $note = trim((string)$note);
    if (gso_text_length($note) < 5) {
        throw new RuntimeException('Опишите причину смены статуса решения минимум в 5 символах.');
    }
    $actor_id = intval($actor_id);
    $proposal_id = intval($proposal_id);

    $pdo->beginTransaction();
    try {
        $stmt = $pdo->prepare("SELECT * FROM gso_proposals WHERE id = ? FOR UPDATE");
        $stmt->execute([$proposal_id]);
        $proposal = $stmt->fetch();
        if (!$proposal) {
            throw new RuntimeException('Решение ГСО не найдено.');
        }
        $previous_status = (string)$proposal['status'];
        if ($previous_status === $new_status) {
            throw new RuntimeException('Решение уже находится в этом статусе.');
        }

        if ($new_status === 'voting') {
            // Новый тур: старые бюллетени остаются за предыдущим туром
            $eligible = max(1, count(gso_eligible_members($pdo)));
            $quorum = gso_quorum_required($eligible);
            $duration = intval($proposal['voting_duration_days']);
            $duration = in_array($duration, [1, 3, 7], true) ? $duration : 3;
            $ends_at = $pdo->query("SELECT NOW() + INTERVAL '" . $duration . " days'")->fetchColumn();
            $stmt = $pdo->prepare("UPDATE gso_proposals SET status = 'voting', vote_round = vote_round + 1, eligible_voters = ?, quorum_required = ?, voting_ends_at = ?, vote_result = NULL, vote_closed_at = NULL, head_account_id = NULL, head_decision = NULL, head_note = NULL, head_decided_at = NULL, implementation_status = 'none', implementation_note = NULL, implemented_by = NULL, implemented_at = NULL, updated_at = NOW() WHERE id = ?");
            $stmt->execute([$eligible, $quorum, $ends_at, $proposal_id]);
        } elseif ($new_status === 'council_review') {
            $stmt = $pdo->prepare("UPDATE gso_proposals SET status = 'council_review', vote_result = COALESCE(vote_result, 'passed'), vote_closed_at = COALESCE(vote_closed_at, NOW()), head_account_id = NULL, head_decision = NULL, head_note = NULL, head_decided_at = NULL, implementation_status = 'none', implementation_note = NULL, implemented_by = NULL, implemented_at = NULL, updated_at = NOW() WHERE id = ?");
            $stmt->execute([$proposal_id]);
        } elseif ($new_status === 'implementation') {
            // Уже одобренное главой совета решение сохраняет его публичное обоснование
            if ((string)($proposal['head_decision'] ?? '') === 'accept') {
                $stmt = $pdo->prepare("UPDATE gso_proposals SET status = 'implementation', implementation_status = 'pending', implementation_note = NULL, implemented_by = NULL, implemented_at = NULL, updated_at = NOW() WHERE id = ?");
                $stmt->execute([$proposal_id]);
            } else {
                $stmt = $pdo->prepare("UPDATE gso_proposals SET status = 'implementation', vote_result = COALESCE(vote_result, 'passed'), vote_closed_at = COALESCE(vote_closed_at, NOW()), head_account_id = ?, head_decision = 'accept', head_note = NULL, head_decided_at = NOW(), implementation_status = 'pending', implementation_note = NULL, implemented_by = NULL, implemented_at = NULL, updated_at = NOW() WHERE id = ?");
                $stmt->execute([$actor_id, $proposal_id]);
            }
        } elseif ($new_status === 'implemented') {
            $stmt = $pdo->prepare("UPDATE gso_proposals SET status = 'implemented', implementation_status = 'completed', implemented_by = ?, implemented_at = NOW(), updated_at = NOW() WHERE id = ?");
            $stmt->execute([$actor_id, $proposal_id]);
        } elseif ($new_status === 'rejected_vote') {
            $stmt = $pdo->prepare("UPDATE gso_proposals SET status = 'rejected_vote', vote_result = 'rejected', vote_closed_at = COALESCE(vote_closed_at, NOW()), implementation_status = 'none', implementation_note = NULL, implemented_by = NULL, implemented_at = NULL, updated_at = NOW() WHERE id = ?");
            $stmt->execute([$proposal_id]);
        } else {
            $stmt = $pdo->prepare("UPDATE gso_proposals SET status = 'rejected_head', head_rejection_count = head_rejection_count + 1, head_account_id = ?, head_decision = 'reject', head_note = NULL, head_decided_at = NOW(), implementation_status = 'none', implementation_note = NULL, implemented_by = NULL, implemented_at = NULL, updated_at = NOW() WHERE id = ?");
            $stmt->execute([$actor_id, $proposal_id]);
        }

        // Служебное событие: причина остаётся в админ-панели и аудите, публично не публикуется
        gso_log_event(
            $pdo,
            $proposal_id,
            'status_override',
            'Глава проекта изменил статус решения с «' . gso_status_label($previous_status, 'ru') . '» на «' . gso_status_label($new_status, 'ru') . '». Причина: ' . $note,
            ['previous_status' => $previous_status, 'new_status' => $new_status, 'note' => $note],
            $actor_id,
            'internal'
        );
        $pdo->commit();
        return $previous_status;
    } catch (Exception $e) {
        if ($pdo->inTransaction()) {
            $pdo->rollBack();
        }
        throw $e;
    }
}

function gso_load_proposals($pdo, $viewer_id = 0, $limit = 100) {
    $limit = max(1, min(200, intval($limit)));
    $stmt = $pdo->prepare("SELECT p.*, a.username AS author_name, h.username AS head_name, h.staff_role AS head_role, h.is_admin AS head_is_admin, i.username AS implementer_name,
            COALESCE(v.yes_votes, 0) AS yes_votes,
            COALESCE(v.no_votes, 0) AS no_votes,
            COALESCE(v.abstain_votes, 0) AS abstain_votes,
            mine.choice AS viewer_choice
        FROM gso_proposals p
        LEFT JOIN accounts a ON a.id = p.author_account_id
        LEFT JOIN accounts h ON h.id = p.head_account_id
        LEFT JOIN accounts i ON i.id = p.implemented_by
        LEFT JOIN (
            SELECT proposal_id, vote_round,
                SUM(CASE WHEN choice = 'yes' THEN 1 ELSE 0 END) AS yes_votes,
                SUM(CASE WHEN choice = 'no' THEN 1 ELSE 0 END) AS no_votes,
                SUM(CASE WHEN choice = 'abstain' THEN 1 ELSE 0 END) AS abstain_votes
            FROM gso_votes
            GROUP BY proposal_id, vote_round
        ) v ON v.proposal_id = p.id AND v.vote_round = p.vote_round
        LEFT JOIN gso_votes mine ON mine.proposal_id = p.id AND mine.vote_round = p.vote_round AND mine.account_id = ?
        ORDER BY CASE p.status WHEN 'voting' THEN 1 WHEN 'council_review' THEN 2 WHEN 'implementation' THEN 3 WHEN 'implemented' THEN 4 WHEN 'rejected_vote' THEN 5 WHEN 'rejected_head' THEN 6 ELSE 7 END, p.created_at DESC
        LIMIT $limit");
    $stmt->execute([intval($viewer_id)]);
    return $stmt->fetchAll();
}

function gso_load_vote_rosters($pdo, $proposals, $eligible_members) {
    $rosters = [];
    $rounds = [];
    $proposal_ids = [];
    foreach ((array)$proposals as $proposal) {
        $proposal_id = intval($proposal['id'] ?? 0);
        if ($proposal_id <= 0) {
            continue;
        }
        $proposal_ids[] = $proposal_id;
        $rounds[$proposal_id] = max(1, intval($proposal['vote_round'] ?? 1));
        $rosters[$proposal_id] = [
            'yes' => [],
            'abstain' => [],
            'no' => [],
            'uncast' => [],
        ];
    }
    if (empty($proposal_ids)) {
        return $rosters;
    }

    $placeholders = implode(',', array_fill(0, count($proposal_ids), '?'));
    $stmt = $pdo->prepare("SELECT v.proposal_id, v.vote_round, v.account_id, v.choice, a.username
        FROM gso_votes AS v
        LEFT JOIN accounts AS a ON a.id = v.account_id
        WHERE v.proposal_id IN ($placeholders)
        ORDER BY a.username ASC, v.account_id ASC");
    $stmt->execute($proposal_ids);
    $voted_accounts = [];
    foreach ($stmt->fetchAll() as $vote) {
        $proposal_id = intval($vote['proposal_id']);
        $account_id = intval($vote['account_id']);
        $choice = (string)$vote['choice'];
        if (!isset($rosters[$proposal_id]) || ($rounds[$proposal_id] ?? 0) !== intval($vote['vote_round']) || !isset($rosters[$proposal_id][$choice])) {
            continue;
        }
        $username = trim((string)($vote['username'] ?? ''));
        $rosters[$proposal_id][$choice][] = [
            'id' => $account_id,
            'username' => $username !== '' ? $username : '#' . $account_id,
        ];
        $voted_accounts[$proposal_id][$account_id] = true;
    }

    foreach ($rosters as $proposal_id => &$roster) {
        foreach ((array)$eligible_members as $member) {
            $account_id = intval($member['id'] ?? 0);
            if ($account_id <= 0 || isset($voted_accounts[$proposal_id][$account_id])) {
                continue;
            }
            $roster['uncast'][] = [
                'id' => $account_id,
                'username' => trim((string)($member['username'] ?? '')) ?: '#' . $account_id,
            ];
        }
    }
    unset($roster);

    return $rosters;
}

// Служебные события главы проекта видны только в админ-панели ($include_internal)
function gso_load_events($pdo, $proposal_ids, $include_internal = false) {
    $proposal_ids = array_values(array_filter(array_map('intval', (array)$proposal_ids)));
    if (empty($proposal_ids)) {
        return [];
    }
    $placeholders = implode(',', array_fill(0, count($proposal_ids), '?'));
    $visibility_filter = $include_internal ? '' : " AND e.visibility = 'public'";
    $stmt = $pdo->prepare("SELECT e.*, a.username AS actor_name FROM gso_events e LEFT JOIN accounts a ON a.id = e.actor_account_id WHERE e.proposal_id IN ($placeholders)$visibility_filter ORDER BY e.created_at ASC, e.id ASC");
    $stmt->execute($proposal_ids);
    $grouped = [];
    foreach ($stmt->fetchAll() as $event) {
        $grouped[intval($event['proposal_id'])][] = $event;
    }
    return $grouped;
}

function gso_status_label($status, $lang = 'ru') {
    $labels = [
        'ru' => [
            'voting' => 'Идёт голосование',
            'council_review' => 'Решение главы совета',
            'implementation' => 'Ожидает реализации',
            'implemented' => 'Реализовано',
            'rejected_vote' => 'Отклонено голосованием',
            'rejected_head' => 'Отклонено главой совета',
        ],
        'uk' => [
            'voting' => 'Триває голосування',
            'council_review' => 'Рішення голови ради',
            'implementation' => 'Очікує реалізації',
            'implemented' => 'Реалізовано',
            'rejected_vote' => 'Відхилено голосуванням',
            'rejected_head' => 'Відхилено головою ради',
        ],
        'en' => [
            'voting' => 'Voting in progress',
            'council_review' => 'Awaiting council-head decision',
            'implementation' => 'Awaiting implementation',
            'implemented' => 'Implemented',
            'rejected_vote' => 'Rejected by vote',
            'rejected_head' => 'Rejected by council head',
        ],
    ];
    return $labels[$lang][$status] ?? (string)$status;
}

function gso_event_label($event_type, $lang = 'ru') {
    $labels = [
        'ru' => [
            'proposal_created' => 'Предложение создано',
            'vote_cast' => 'Голос учтён',
            'vote_closed' => 'Голосование завершено',
            'head_decision' => 'Решение главы совета',
            'head_rejected_once' => 'Единственный отказ главы',
            'revote_started' => 'Повторное голосование',
            'implementation_started' => 'Взято в работу',
            'implementation_deferred' => 'Реализация отложена',
            'implementation_completed' => 'Реализовано',
            'status_override' => 'Статус изменён главой проекта',
        ],
        'uk' => [
            'proposal_created' => 'Пропозицію створено',
            'vote_cast' => 'Голос враховано',
            'vote_closed' => 'Голосування завершено',
            'head_decision' => 'Рішення голови ради',
            'head_rejected_once' => 'Єдина відмова голови',
            'revote_started' => 'Повторне голосування',
            'implementation_started' => 'Взято в роботу',
            'implementation_deferred' => 'Реалізацію відкладено',
            'implementation_completed' => 'Реалізовано',
            'status_override' => 'Статус змінено головою проєкту',
        ],
        'en' => [
            'proposal_created' => 'Proposal created',
            'vote_cast' => 'Vote recorded',
            'vote_closed' => 'Vote closed',
            'head_decision' => 'Council-head decision',
            'head_rejected_once' => 'Council-head rejection',
            'revote_started' => 'New vote started',
            'implementation_started' => 'Implementation started',
            'implementation_deferred' => 'Implementation deferred',
            'implementation_completed' => 'Implemented',
            'status_override' => 'Status changed by project lead',
        ],
    ];
    return $labels[$lang][$event_type] ?? (string)$event_type;
}
