<?php

const ORION_PLAYER_PETITION_SIGNATURE_THRESHOLD = 50;
const ORION_PLAYER_PETITION_VOTING_DAYS = 3;
const ORION_PLAYER_PETITION_COOLDOWN_DAYS = 3;

function ensure_player_petition_schema($pdo) {
    $pdo->exec("CREATE TABLE IF NOT EXISTS player_petitions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        author_account_id BIGINT NOT NULL,
        title VARCHAR(180) NOT NULL,
        description TEXT NOT NULL,
        expected_result TEXT NOT NULL,
        status VARCHAR(32) NOT NULL DEFAULT 'collecting',
        signature_count INTEGER NOT NULL DEFAULT 0,
        signature_threshold INTEGER NOT NULL DEFAULT 50,
        gso_proposal_id BIGINT NULL,
        submitted_ip VARCHAR(45) NULL,
        promoted_at TIMESTAMP NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)
    )");
    $pdo->exec("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uniq_player_petition_gso') THEN ALTER TABLE player_petitions ADD CONSTRAINT uniq_player_petition_gso UNIQUE (gso_proposal_id); END IF; END $$");
    $pdo->exec("CREATE INDEX IF NOT EXISTS idx_player_petitions_status ON player_petitions (status, created_at)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS idx_player_petitions_author ON player_petitions (author_account_id, created_at)");
    $pdo->exec("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_player_petitions_updated_at') THEN CREATE TRIGGER trg_player_petitions_updated_at BEFORE UPDATE ON player_petitions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column(); END IF; END $$");

    $pdo->exec("CREATE TABLE IF NOT EXISTS player_petition_signatures (
        petition_id BIGINT NOT NULL,
        account_id BIGINT NOT NULL,
        ip_address VARCHAR(45) NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (petition_id, account_id)
    )");
    $pdo->exec("CREATE INDEX IF NOT EXISTS idx_player_petition_signatures_account ON player_petition_signatures (account_id, created_at)");
}

function player_petition_text_length($value) {
    return function_exists('mb_strlen') ? mb_strlen((string)$value, 'UTF-8') : strlen((string)$value);
}

function player_petition_signature_progress($signature_count, $signature_threshold = ORION_PLAYER_PETITION_SIGNATURE_THRESHOLD) {
    $signature_count = max(0, intval($signature_count));
    $signature_threshold = max(1, intval($signature_threshold));
    return min(100, max(0, (int)round(($signature_count / $signature_threshold) * 100)));
}

function player_petition_has_reached_threshold($signature_count, $signature_threshold = ORION_PLAYER_PETITION_SIGNATURE_THRESHOLD) {
    return intval($signature_count) >= max(1, intval($signature_threshold));
}

function player_petition_status_from_gso_status($status) {
    $status = (string)$status;
    if (in_array($status, ['voting', 'council_review', 'implementation', 'implemented'], true)) {
        return $status;
    }
    if (in_array($status, ['rejected_vote', 'rejected_head'], true)) {
        return 'rejected';
    }
    return null;
}

function player_petition_status_label($status, $lang = 'ru') {
    $labels = [
        'ru' => [
            'collecting' => 'Сбор подписей',
            'voting' => 'На голосовании руководства',
            'council_review' => 'На решении руководства',
            'implementation' => 'Принято к реализации',
            'implemented' => 'Реализовано',
            'rejected' => 'Отклонено',
        ],
        'uk' => [
            'collecting' => 'Збір підписів',
            'voting' => 'На голосуванні керівництва',
            'council_review' => 'На рішенні керівництва',
            'implementation' => 'Прийнято до реалізації',
            'implemented' => 'Реалізовано',
            'rejected' => 'Відхилено',
        ],
        'en' => [
            'collecting' => 'Collecting signatures',
            'voting' => 'Council vote in progress',
            'council_review' => 'Awaiting council decision',
            'implementation' => 'Accepted for implementation',
            'implemented' => 'Implemented',
            'rejected' => 'Rejected',
        ],
    ];
    return $labels[$lang][$status] ?? (string)$status;
}

function player_petition_localize_message($message, $lang = null) {
    if ($lang === null) {
        $lang = function_exists('current_lang') ? current_lang() : 'ru';
    }
    $lang = in_array($lang, ['ru', 'uk', 'en'], true) ? $lang : 'ru';
    if ($lang === 'ru') {
        return (string)$message;
    }
    $translations = [
        'uk' => [
            'Недостаточно подписей для передачи предложения руководству.' => 'Недостатньо підписів, щоб передати пропозицію керівництву.',
            'Не удалось передать предложение руководству.' => 'Не вдалося передати пропозицію керівництву.',
            'Войдите в аккаунт, чтобы создать предложение.' => 'Увійдіть в акаунт, щоб створити пропозицію.',
            'Название предложения должно содержать от 8 до 180 символов.' => 'Назва пропозиції має містити від 8 до 180 символів.',
            'Описание предложения должно содержать от 30 до 10 000 символов.' => 'Опис пропозиції має містити від 30 до 10 000 символів.',
            'Опишите ожидаемый результат минимум в 10 символах.' => 'Опишіть очікуваний результат щонайменше у 10 символах.',
            'Аккаунт не найден.' => 'Акаунт не знайдено.',
            'Следующее предложение можно создать только через 3 дня после предыдущего.' => 'Наступну пропозицію можна створити лише через 3 дні після попередньої.',
            'У вас уже есть активное предложение. Дождитесь его решения.' => 'У вас уже є активна пропозиція. Дочекайтеся її рішення.',
            'Предложение или аккаунт не найдены.' => 'Пропозицію або акаунт не знайдено.',
            'Предложение не найдено.' => 'Пропозицію не знайдено.',
            'Сбор подписей по этому предложению уже завершён.' => 'Збір підписів за цією пропозицією вже завершено.',
            'Вы уже подписали это предложение.' => 'Ви вже підписали цю пропозицію.',
        ],
        'en' => [
            'Недостаточно подписей для передачи предложения руководству.' => 'There are not enough signatures to submit the proposal to the council.',
            'Не удалось передать предложение руководству.' => 'The proposal could not be submitted to the council.',
            'Войдите в аккаунт, чтобы создать предложение.' => 'Sign in to create a proposal.',
            'Название предложения должно содержать от 8 до 180 символов.' => 'The proposal title must contain between 8 and 180 characters.',
            'Описание предложения должно содержать от 30 до 10 000 символов.' => 'The proposal description must contain between 30 and 10,000 characters.',
            'Опишите ожидаемый результат минимум в 10 символах.' => 'Describe the expected result in at least 10 characters.',
            'Аккаунт не найден.' => 'Account not found.',
            'Следующее предложение можно создать только через 3 дня после предыдущего.' => 'You can create the next proposal only 3 days after the previous one.',
            'У вас уже есть активное предложение. Дождитесь его решения.' => 'You already have an active proposal. Wait for its decision.',
            'Предложение или аккаунт не найдены.' => 'Proposal or account not found.',
            'Предложение не найдено.' => 'Proposal not found.',
            'Сбор подписей по этому предложению уже завершён.' => 'Signature collection for this proposal has ended.',
            'Вы уже подписали это предложение.' => 'You have already signed this proposal.',
        ],
    ];
    return $translations[$lang][$message] ?? (string)$message;
}

function player_petition_has_open_for_author($pdo, $author_id) {
    $stmt = $pdo->prepare("SELECT COUNT(*) FROM player_petitions WHERE author_account_id = ? AND status IN ('collecting', 'voting', 'council_review', 'implementation')");
    $stmt->execute([intval($author_id)]);
    return intval($stmt->fetchColumn()) > 0;
}

function player_petition_promote_locked($pdo, $petition) {
    $petition_id = intval($petition['id'] ?? 0);
    $signature_count = intval($petition['signature_count'] ?? 0);
    $signature_threshold = max(1, intval($petition['signature_threshold'] ?? ORION_PLAYER_PETITION_SIGNATURE_THRESHOLD));
    if ($petition_id <= 0 || !player_petition_has_reached_threshold($signature_count, $signature_threshold)) {
        throw new RuntimeException('Недостаточно подписей для передачи предложения руководству.');
    }
    if (intval($petition['gso_proposal_id'] ?? 0) > 0) {
        return intval($petition['gso_proposal_id']);
    }

    $members = gso_eligible_members($pdo);
    $eligible_voters = max(1, count($members));
    $quorum_required = gso_quorum_required($eligible_voters);
    $duration_days = ORION_PLAYER_PETITION_VOTING_DAYS;
    $ends_at = $pdo->query("SELECT NOW() + INTERVAL '" . $duration_days . " days'")->fetchColumn();

    $stmt = $pdo->prepare("INSERT INTO gso_proposals (author_account_id, title, description, expected_result, status, eligible_voters, quorum_required, voting_duration_days, voting_ends_at, vote_round, head_rejection_count, implementation_status, created_at, updated_at) VALUES (?, ?, ?, ?, 'voting', ?, ?, ?, ?, 1, 0, 'none', NOW(), NOW())");
    $stmt->execute([
        intval($petition['author_account_id']),
        (string)$petition['title'],
        (string)$petition['description'],
        (string)$petition['expected_result'],
        $eligible_voters,
        $quorum_required,
        $duration_days,
        $ends_at,
    ]);
    $gso_proposal_id = intval($pdo->lastInsertId());

    gso_log_event(
        $pdo,
        $gso_proposal_id,
        'proposal_created',
        'Инициатива игрока собрала ' . $signature_count . ' подписей и передана руководству на голосование.',
        [
            'source' => 'player_petition',
            'petition_id' => $petition_id,
            'signature_count' => $signature_count,
            'signature_threshold' => $signature_threshold,
        ],
        intval($petition['author_account_id'])
    );

    $stmt = $pdo->prepare("UPDATE player_petitions SET status = 'voting', signature_count = ?, gso_proposal_id = ?, promoted_at = NOW(), updated_at = NOW() WHERE id = ? AND status = 'collecting'");
    $stmt->execute([$signature_count, $gso_proposal_id, $petition_id]);
    if ($stmt->rowCount() !== 1) {
        throw new RuntimeException('Не удалось передать предложение руководству.');
    }
    return $gso_proposal_id;
}

function player_petition_create($pdo, $author_id, $title, $description, $expected_result, $submitted_ip = '') {
    $author_id = intval($author_id);
    $title = trim((string)$title);
    $description = trim((string)$description);
    $expected_result = trim((string)$expected_result);

    if ($author_id <= 0) {
        throw new RuntimeException('Войдите в аккаунт, чтобы создать предложение.');
    }
    if (player_petition_text_length($title) < 8 || player_petition_text_length($title) > 180) {
        throw new RuntimeException('Название предложения должно содержать от 8 до 180 символов.');
    }
    if (player_petition_text_length($description) < 30 || player_petition_text_length($description) > 10000) {
        throw new RuntimeException('Описание предложения должно содержать от 30 до 10 000 символов.');
    }
    if (player_petition_text_length($expected_result) < 10 || player_petition_text_length($expected_result) > 4000) {
        throw new RuntimeException('Опишите ожидаемый результат минимум в 10 символах.');
    }

    player_petition_sync_statuses($pdo);
    $pdo->beginTransaction();
    try {
        $stmt = $pdo->prepare("SELECT id FROM accounts WHERE id = ? FOR UPDATE");
        $stmt->execute([$author_id]);
        if (!$stmt->fetchColumn()) {
            throw new RuntimeException('Аккаунт не найден.');
        }
        $stmt = $pdo->prepare("SELECT created_at + INTERVAL '" . ORION_PLAYER_PETITION_COOLDOWN_DAYS . " days' AS next_available_at FROM player_petitions WHERE author_account_id = ? ORDER BY created_at DESC, id DESC LIMIT 1 FOR UPDATE");
        $stmt->execute([$author_id]);
        $last_petition = $stmt->fetch();
        $next_available_at = strtotime((string)($last_petition['next_available_at'] ?? ''));
        if ($next_available_at !== false && $next_available_at > time()) {
            throw new RuntimeException('Следующее предложение можно создать только через 3 дня после предыдущего.');
        }
        if (player_petition_has_open_for_author($pdo, $author_id)) {
            throw new RuntimeException('У вас уже есть активное предложение. Дождитесь его решения.');
        }

        $threshold = ORION_PLAYER_PETITION_SIGNATURE_THRESHOLD;
        $stmt = $pdo->prepare("INSERT INTO player_petitions (author_account_id, title, description, expected_result, status, signature_count, signature_threshold, submitted_ip, created_at, updated_at) VALUES (?, ?, ?, ?, 'collecting', 1, ?, ?, NOW(), NOW())");
        $stmt->execute([
            $author_id,
            $title,
            $description,
            $expected_result,
            $threshold,
            substr((string)$submitted_ip, 0, 45),
        ]);
        $petition_id = intval($pdo->lastInsertId());
        $stmt = $pdo->prepare("INSERT INTO player_petition_signatures (petition_id, account_id, ip_address, created_at) VALUES (?, ?, ?, NOW())");
        $stmt->execute([$petition_id, $author_id, substr((string)$submitted_ip, 0, 45)]);
        $pdo->commit();
        return $petition_id;
    } catch (Exception $e) {
        if ($pdo->inTransaction()) {
            $pdo->rollBack();
        }
        throw $e;
    }
}

function player_petition_sign($pdo, $petition_id, $account_id, $ip_address = '') {
    $petition_id = intval($petition_id);
    $account_id = intval($account_id);
    if ($petition_id <= 0 || $account_id <= 0) {
        throw new RuntimeException('Предложение или аккаунт не найдены.');
    }

    $pdo->beginTransaction();
    try {
        $stmt = $pdo->prepare("SELECT * FROM player_petitions WHERE id = ? FOR UPDATE");
        $stmt->execute([$petition_id]);
        $petition = $stmt->fetch();
        if (!$petition) {
            throw new RuntimeException('Предложение не найдено.');
        }
        if ((string)$petition['status'] !== 'collecting') {
            throw new RuntimeException('Сбор подписей по этому предложению уже завершён.');
        }

        $stmt = $pdo->prepare("SELECT account_id FROM player_petition_signatures WHERE petition_id = ? AND account_id = ? LIMIT 1");
        $stmt->execute([$petition_id, $account_id]);
        if ($stmt->fetchColumn() !== false) {
            throw new RuntimeException('Вы уже подписали это предложение.');
        }

        $stmt = $pdo->prepare("INSERT INTO player_petition_signatures (petition_id, account_id, ip_address, created_at) VALUES (?, ?, ?, NOW())");
        $stmt->execute([$petition_id, $account_id, substr((string)$ip_address, 0, 45)]);
        $signature_count = intval($petition['signature_count']) + 1;
        $petition['signature_count'] = $signature_count;
        $gso_proposal_id = 0;
        if (player_petition_has_reached_threshold($signature_count, $petition['signature_threshold'])) {
            $gso_proposal_id = player_petition_promote_locked($pdo, $petition);
        } else {
            $stmt = $pdo->prepare("UPDATE player_petitions SET signature_count = ?, updated_at = NOW() WHERE id = ?");
            $stmt->execute([$signature_count, $petition_id]);
        }
        $pdo->commit();
        return [
            'signature_count' => $signature_count,
            'signature_threshold' => max(1, intval($petition['signature_threshold'])),
            'promoted' => $gso_proposal_id > 0,
            'gso_proposal_id' => $gso_proposal_id,
        ];
    } catch (Exception $e) {
        if ($pdo->inTransaction()) {
            $pdo->rollBack();
        }
        throw $e;
    }
}

function player_petition_sync_statuses($pdo) {
    try {
        gso_sync_expired_votes($pdo);
        $stmt = $pdo->query("SELECT p.id, p.status, g.status AS gso_status FROM player_petitions p INNER JOIN gso_proposals g ON g.id = p.gso_proposal_id WHERE p.gso_proposal_id IS NOT NULL AND p.status <> 'collecting'");
        $update = $pdo->prepare("UPDATE player_petitions SET status = ?, updated_at = NOW() WHERE id = ?");
        foreach ($stmt->fetchAll() as $row) {
            $next_status = player_petition_status_from_gso_status($row['gso_status'] ?? '');
            if ($next_status !== null && $next_status !== (string)$row['status']) {
                $update->execute([$next_status, intval($row['id'])]);
            }
        }
    } catch (Exception $e) {
        error_log('Player petition status synchronization error: ' . $e->getMessage());
    }
}

function player_petition_load($pdo, $viewer_id = 0, $limit = 100) {
    $limit = max(1, min(200, intval($limit)));
    $stmt = $pdo->prepare("SELECT p.*, a.username AS author_name, CASE WHEN s.account_id IS NULL THEN 0 ELSE 1 END AS viewer_signed
        FROM player_petitions p
        LEFT JOIN accounts a ON a.id = p.author_account_id
        LEFT JOIN player_petition_signatures s ON s.petition_id = p.id AND s.account_id = ?
        ORDER BY CASE p.status WHEN 'collecting' THEN 1 WHEN 'voting' THEN 2 WHEN 'council_review' THEN 3 WHEN 'implementation' THEN 4 WHEN 'implemented' THEN 5 WHEN 'rejected' THEN 6 ELSE 7 END, p.created_at DESC
        LIMIT $limit");
    $stmt->execute([intval($viewer_id)]);
    return $stmt->fetchAll();
}
