<?php

// Shared bilingual roadmap content for the homepage preview and the full page.
function orion_roadmap_data($lang = null) {
    if ($lang === null) {
        $lang = function_exists('current_lang') ? current_lang() : 'ru';
    }

    if ($lang === 'uk') {
        return [
            'eyebrow' => 'ПЛАН ДО ЗАПУСКУ · 0.8.2',
            'title' => 'Роадмап сервера 0.8.2',
            'description' => 'Від живого ангара до відкритих дверей сервера. Іде останній тиждень: бій замкнуто повним циклом, живий прогін пройдено на 120 клієнтах, і до 30 серпня лишилися переїзд бази та збірка клієнта.',
            'updated' => 'План: 15 липня – 30 серпня 2026',
            'progress_label' => 'Загальний прогрес',
            'progress_note' => '5 із 6 етапів завершено',
            'progress_value' => 88,
            'current_id' => 'launch',
            'next_id' => 'launch',
            'goal_id' => 'launch',
            'current_label' => 'Поточний фокус',
            'next_label' => 'Далі за планом',
            'details_label' => 'Результат етапу',
            'open_label' => 'Відкрити повний роадмап',
            'all_stages_label' => 'Усі етапи',
            'timeline_label' => 'Спринт до запуску',
            'timeline_title' => 'Півтора місяця до відкритих дверей',
            'timeline_description' => 'Кожен етап закінчується результатом, який можна перевірити в клієнті або на сервері. Порядок етапів переставлено за фактом розробки: спершу поїхав і вистрілив танк, потім за нього узялися екіпаж і нагорода, а окремий dbmgr, магазин і дерево досліджень поїхали за дату відкриття.',
            'summary' => [
                ['value' => '238', 'label' => 'коміти сервера'],
                ['value' => '30.08', 'label' => 'дата запуску'],
                ['value' => '253', 'label' => 'танки вже в ангарі'],
                ['value' => '120', 'label' => 'гравців у живому прогоні'],
            ],
            'statuses' => [
                'done' => 'Завершено',
                'current' => 'У роботі',
                'planned' => 'Заплановано',
                'goal' => 'Запуск',
            ],
            'phases' => [
                [
                    'id' => 'start',
                    'number' => '00',
                    'period' => '15–18 липня 2026',
                    'phase' => 'Стартовий спринт',
                    'title' => 'З нуля до живого ангара',
                    'lead' => 'За 3,5 дні та 122 коміти зібрано базовий серверний контур і повний шлях входу гравця до 3D-ангара.',
                    'status' => 'done',
                    'meta' => ['3,5 дні', '122 коміти'],
                    'tasks' => [
                        'Протокол BigWorld/Mercury з нуля: UDP-фреймінг, reliable-шар (seq/ack), фрагменти, RSA-логін, Blowfish-шифрування каналу та внутрішній RPC між процесами.',
                        'Повний login-хендшейк → baseapp → сутність Account → showGUI/showLobby → 3D-ангар.',
                        'Усі 253 танки гри в каруселі: compactDescr з ігрових XML, ціни магазину, стрімінг інвентаря та heartbeat проти розриву сесії.',
                        'БД-авторизація: логін і пароль звіряються з accounts (sha256, як на сайті), а валюта, ім’я, преміум і клан надходять з MySQL.',
                    ],
                ],
                [
                    'id' => 'week-1',
                    'number' => '01',
                    'period' => '19–26 липня',
                    'phase' => 'Тиждень 1',
                    'title' => 'Особистий гараж і перший бій',
                    'lead' => 'Ангар став особистим — а на третій день тижня танк уперше виїхав на арену, на два тижні раніше плану.',
                    'status' => 'done',
                    'meta' => ['8 днів', '36 комітів'],
                    'tasks' => [
                        'Екіпаж і модулі танків приходять з БД: в ангарі стоїть реальна комплектація, а не дефолтна.',
                        'У каруселі — танки конкретного акаунта: справжні slots, berths і розкладка спорядження.',
                        'Обладнання й боєкомплект: досилачі, вентиляція, оптика та снаряди всіх типів купуються і зберігаються в БД.',
                        'Живий лічильник онлайну з оновленням кожні 15 секунд.',
                        '21 липня — перший бій: вхід на арену, сутність Avatar, спавн танка й карта «Малинівка».',
                        'Рух став серверним: forcedPosition, рельєф, колізії та плавна фізика замість клієнтської відсебеньки.',
                        'Виділений dbmgr і міграцію 2520 акаунтів свідомо перенесено на етап економіки — спершу закриваємо бій.',
                    ],
                ],
                [
                    'id' => 'week-2',
                    'number' => '02',
                    'period' => '27 липня – 3 серпня',
                    'phase' => 'Тиждень 2',
                    'title' => 'Бій набирає ваги',
                    'lead' => 'Етап завершено: стрільба, пробиття та руйнування зібралися в повноцінний бій, черга й балансувальник ведуть гравця на арену, а сервер навчився оновлювати код без перезапуску.',
                    'status' => 'done',
                    'meta' => ['8 днів', '13 комітів'],
                    'tasks' => [
                        'Стрільба з перезарядкою та чергою пострілів, стандартний режим прицілу.',
                        'Наведення башти й гармати синхронно із сервером.',
                        'Черга перед боєм і балансувальник: вікно очікування з таймером і складом черги за рівнями та класами.',
                        'Один режим — одна база: зустрічний бій і маска видимості об’єктів карти замість баз усіх режимів одразу.',
                        'Модель пробиття та пошкоджень: броня, кути, тип снаряда, влучання по модулях; крити модулів — гусениця збивається, боєукладка детонує.',
                        'Руйнівне оточення: ламаються дерева, будівлі та грубі паркани, ефекти влучання по своєму танку.',
                        'Мультиплеер: кілька танків на одній арені, снаряди не пролітають крізь чужі корпуси, ворожі танки видні в табі обох клієнтів, стрільба на різних висотах.',
                        'Завантажується будь-яка карта, а не лише «Малинівка».',
                        'Гаряче перезавантаження коду сервера без перезапуску; 4-й антимонолітний прохід — розрізано 9 модулів.',
                    ],
                ],
                [
                    'id' => 'week-3',
                    'number' => '03',
                    'period' => '4–17 серпня',
                    'phase' => 'Тижні 3–4',
                    'title' => 'Розвідка, кінець раунду і тік на 100+',
                    'lead' => 'Борг за даними знову відклали: вікно пішло на те, щоб бій став чесним — засвіт, кущі, кінець раунду — і щоб тік не розсипався на сотні гравців.',
                    'status' => 'done',
                    'meta' => ['14 днів', '23 коміти'],
                    'tasks' => [
                        'Засвіт: ворога видно лише поки його справді бачать; кущі маскують, оптика й огляд башти виміряні по клієнту.',
                        'Кінець раунду, маска баз десятковим текстом, просвіт і спільні руйнування; переїзд через уламки тримає весь профіль висоти.',
                        'Крити ламають саме те, у що влучили — промінь проти трикутників замість зон.',
                        'Відлік перед боєм, чистий вихід у ангар, гармата, що сама заряджається, коло розкиду та форма розсіювання.',
                        'Тік тримає 100+ гравців, трупи лишаються на полі; мітку часу кадру рухає setGameTime — знайдено розтином exe.',
                        'Сервер слухає клієнтів і на localhost, і на зовнішній адресі.',
                    ],
                ],
                [
                    'id' => 'battle',
                    'number' => '04',
                    'period' => '18–24 серпня',
                    'phase' => 'Передзапусковий тиждень',
                    'title' => 'У БІЙ — екіпаж, нагорода і власний res',
                    'lead' => 'Бій замкнуто: підвіска тримає корпус, екіпаж має перки, за бій платять у гаманець, а сервер везе власний res і більше не є надбудовою над встановленою грою.',
                    'status' => 'done',
                    'meta' => ['7 днів', '30 комітів'],
                    'tasks' => [
                        'Корпус лежить на гусеницях: пляма контакту — відрізок, корпус лягає на її площину, спуск не пилить, яма не ковтає танк.',
                        'Наїзд ламає все — паркан падає від дотику; танк більше не лізе поверхами в зруйновані будинки, заїзд на пагорби Хіммельсдорфа.',
                        'Ефективні ТТХ: обладнання, перки та крити реально міняють характеристики машини.',
                        'Перки й пересадка екіпажу, вікно підсумків бою, нагорода за бій потрапляє в гаманець гравця.',
                        'Аудит персистенції: перки, обладнання й модулі справді лягають у базу.',
                        'Командний чат у бою, суцільні танки й таран; знято два краші клієнта — на старті бою й на кінці раунду.',
                        'Власний res сервера (70,8 МіБ витягнуто з клієнта) і redirect_config під заданий IP.',
                    ],
                ],
                [
                    'id' => 'launch',
                    'number' => '05',
                    'period' => '25–30 серпня',
                    'phase' => 'Запуск',
                    'title' => '30 серпня — двері відчинено',
                    'lead' => 'Останній тиждень уже йде. Стрес-прогін пройдено на 120 живих клієнтах, черга й шарди на місці — лишилися переїзд бази, збірка клієнта й чергування.',
                    'status' => 'goal',
                    'meta' => ['6 днів', '30 серпня'],
                    'tasks' => [
                        'Пройдено: живий наскрізний прогін — 120 гравців, 3 шарди, 6 арен. Посадка в бій p50 0,70 с · p95 1,17 с, 120 зі 120 у бою, тік їзди 33,6–33,8 мс проти цілі 33,3.',
                        'Пройдено: черга без очікування і N шардів baseapp — хвиля їде достроково, підсадка в бій, що вже триває; АКи склеєні, 137 → 68 надійних пакетів/с.',
                        'Пройдено: вертикаль фізики переписано з нуля (корпус на десяти ресорах), у ротації Прохоровка й Хребет Дракона, респаун — від власної бази команди.',
                        'Лишилось: перенесення 2520 акаунтів сайту в бойову базу і звірка балансів перед першим днем.',
                        'Лишилось: збірка клієнта й лаунчер на сторінці завантаження — один архів, один запуск, без ручних правок конфігів.',
                        'Лишилось: моніторинг і чергування — логи, метрики онлайну та швидкий відкат оновлення без зупинки сервера.',
                        'За дату відкриття перенесено: окремий dbmgr, купівля танків у магазині та дерево досліджень.',
                        '30 серпня 2026 — сервер відкрито для всіх: реєстрація, ангар і бій доступні без запрошень.',
                    ],
                ],
            ],
        ];
    }

    if ($lang === 'en') {
        return [
            'eyebrow' => 'PLAN TO LAUNCH · 0.8.2',
            'title' => 'Orion server roadmap 0.8.2',
            'description' => 'From a live garage to open doors. The final week is running: the battle loop is closed, a live run passed with 120 clients, and what is left before August 30 is the database move and the client build.',
            'updated' => 'Plan: July 15 – August 30, 2026',
            'progress_label' => 'Overall progress',
            'progress_note' => '5 of 6 stages complete',
            'progress_value' => 88,
            'current_id' => 'launch',
            'next_id' => 'launch',
            'goal_id' => 'launch',
            'current_label' => 'Current focus',
            'next_label' => 'Next on the plan',
            'details_label' => 'Stage result',
            'open_label' => 'Open the full roadmap',
            'all_stages_label' => 'All stages',
            'timeline_label' => 'Sprint to launch',
            'timeline_title' => 'Six weeks to open doors',
            'timeline_description' => 'Each stage ends with a result that can be checked in the client or on the server. The stage order follows actual development: first the tank moved and fired, then the crew and the reward were built on top of it, and the separate dbmgr, the shop, and the research tree moved past the opening date.',
            'summary' => [
                ['value' => '238', 'label' => 'server commits'],
                ['value' => '30.08', 'label' => 'launch date'],
                ['value' => '253', 'label' => 'tanks already in the garage'],
                ['value' => '120', 'label' => 'players in the live run'],
            ],
            'statuses' => [
                'done' => 'Complete',
                'current' => 'In progress',
                'planned' => 'Planned',
                'goal' => 'Launch',
            ],
            'phases' => [
                [
                    'id' => 'start',
                    'number' => '00',
                    'period' => 'July 15–18, 2026',
                    'phase' => 'Kickoff sprint',
                    'title' => 'From zero to a live garage',
                    'lead' => 'In 3.5 days and 122 commits, we built the base server layer and the full path from player login to the 3D garage.',
                    'status' => 'done',
                    'meta' => ['3.5 days', '122 commits'],
                    'tasks' => [
                        'BigWorld/Mercury protocol from scratch: UDP framing, a reliable layer (seq/ack), fragments, RSA login, Blowfish channel encryption, and internal RPC between processes.',
                        'Complete login handshake → baseapp → Account entity → showGUI/showLobby → 3D garage.',
                        'All 253 game tanks in the carousel: compactDescr from game XML, shop prices, inventory streaming, and a heartbeat to prevent session drops.',
                        'Database authentication: login and password are checked against accounts (sha256, as on the site), while currency, name, premium, and clan come from MySQL.',
                    ],
                ],
                [
                    'id' => 'week-1',
                    'number' => '01',
                    'period' => 'July 19–26',
                    'phase' => 'Week 1',
                    'title' => 'Personal garage and first battle',
                    'lead' => 'The garage became personal, and on the third day of the week a tank entered the arena for the first time, two weeks ahead of plan.',
                    'status' => 'done',
                    'meta' => ['8 days', '36 commits'],
                    'tasks' => [
                        'Tank crews and modules come from the database: the garage shows a real loadout, not a default one.',
                        'The carousel shows the account’s actual tanks with real slots, berths, and equipment layout.',
                        'Equipment and ammunition: rammers, ventilation, optics, and shells of every type are bought and stored in the database.',
                        'Live online counter updated every 15 seconds.',
                        'July 21 — first battle: arena entry, Avatar entity, tank spawn, and the Malinovka map.',
                        'Movement became server-authoritative: forcedPosition, terrain, collisions, and smooth physics instead of client-side improvisation.',
                        'A dedicated dbmgr and migration of 2,520 accounts were deliberately moved to the economy stage — battle comes first.',
                    ],
                ],
                [
                    'id' => 'week-2',
                    'number' => '02',
                    'period' => 'July 27 – August 3',
                    'phase' => 'Week 2',
                    'title' => 'Battle gains weight',
                    'lead' => 'Stage complete: firing, penetration, and destruction came together into a full battle, the queue and balancer walk the player into the arena, and the server learned to update its code without a restart.',
                    'status' => 'done',
                    'meta' => ['8 days', '13 commits'],
                    'tasks' => [
                        'Reloading and burst fire with the standard aiming mode.',
                        'Turret and gun traverse synchronized with the server.',
                        'Pre-battle queue and balancer: a waiting window with a timer and the queue composition by tier and class.',
                        'One mode — one base: encounter battle and a map object visibility mask instead of the bases of every mode at once.',
                        'Penetration and damage model: armor, angles, shell type, and module hits; module crits — tracks get knocked off and ammo racks detonate.',
                        'Destructible environment: trees, buildings, and sturdy fences break; hit effects on your own tank.',
                        'Multiplayer: several tanks on one arena, shells do not pass through other hulls, enemy tanks show up in the tabs of both clients, and combat works at different elevations.',
                        'Any map loads, not just Malinovka.',
                        'Hot reload of server code without a restart; the fourth anti-monolith pass cut the codebase into 9 modules.',
                    ],
                ],
                [
                    'id' => 'week-3',
                    'number' => '03',
                    'period' => 'August 4–17',
                    'phase' => 'Weeks 3–4',
                    'title' => 'Spotting, round end, and a 100+ tick',
                    'lead' => 'The data debt was deferred again: the window went into making the battle honest — spotting, bushes, end of round — and into a tick that does not fall apart under a hundred players.',
                    'status' => 'done',
                    'meta' => ['14 days', '23 commits'],
                    'tasks' => [
                        'Spotting: an enemy is visible only while actually seen; bushes camouflage, and optics and turret view range are measured against the client.',
                        'End of round, base masks as decimal text, clearance and shared destruction; driving over rubble keeps the whole height profile.',
                        'Critical hits break exactly what was hit — a ray against triangles instead of zones.',
                        'Pre-battle countdown, a clean exit to the garage, a gun that reloads itself, the dispersion circle, and the scatter shape.',
                        'The tick holds 100+ players and wrecks stay on the field; the frame timestamp is moved by setGameTime — found by dissecting the exe.',
                        'The server listens for clients on both localhost and an external address.',
                    ],
                ],
                [
                    'id' => 'battle',
                    'number' => '04',
                    'period' => 'August 18–24',
                    'phase' => 'Pre-launch week',
                    'title' => 'INTO BATTLE — crew, reward, and its own res',
                    'lead' => 'The loop is closed: the suspension carries the hull, the crew has perks, a battle pays into the wallet, and the server ships its own res instead of being an add-on over an installed game.',
                    'status' => 'done',
                    'meta' => ['7 days', '30 commits'],
                    'tasks' => [
                        'The hull rests on its tracks: the contact patch is a segment, the hull settles onto its plane, descents no longer saw, and a small hole no longer swallows the tank.',
                        'Driving over things breaks them — a fence falls on contact; the tank no longer climbs floors inside ruined buildings, and it can take the Himmelsdorf hills.',
                        'Effective stats: equipment, perks, and crits actually change the vehicle characteristics.',
                        'Crew perks and reseating, the post-battle results window, and the battle reward landing in the player wallet.',
                        'Persistence audit: perks, equipment, and modules really do reach the database.',
                        'Team chat in battle, solid tanks and ramming; two client crashes fixed — at battle start and at round end.',
                        'The server ships its own res (70.8 MiB extracted from the client) and a redirect_config for a given IP.',
                    ],
                ],
                [
                    'id' => 'launch',
                    'number' => '05',
                    'period' => 'August 25–30',
                    'phase' => 'Launch',
                    'title' => 'August 30 — doors open',
                    'lead' => 'The last week is already running. The stress run passed with 120 live clients and the queue and shards are in place — what remains is the database move, the client build, and on-call duty.',
                    'status' => 'goal',
                    'meta' => ['6 days', 'August 30'],
                    'tasks' => [
                        'Done: a live end-to-end run — 120 players, 3 shards, 6 arenas. Queue to spawn p50 0.70 s · p95 1.17 s, 120 of 120 in battle, drive tick 33.6–33.8 ms against a 33.3 target.',
                        'Done: a queue without waiting and N baseapp shards — a wave leaves early, players join a battle already in progress, and acks are coalesced from 137 to 68 reliable packets per second.',
                        'Done: the physics vertical rewritten from scratch (hull on ten springs), Prokhorovka and Dragon Ridge in rotation, and respawn from the team\'s own base.',
                        'Left: moving the 2,520 site accounts into the production database and reconciling balances before day one.',
                        'Left: the client build and launcher on the download page — one archive, one run, no manual config edits.',
                        'Left: monitoring and on-call duty — logs, online metrics, and a fast update rollback without stopping the server.',
                        'Moved past the opening date: the separate dbmgr, buying tanks in the shop, and the research tree.',
                        'August 30, 2026 — the server opens for everyone: registration, garage, and battle available without invites.',
                    ],
                ],
            ],
        ];
    }

    return [
        'eyebrow' => 'ПЛАН ДО ЗАПУСКА · 0.8.2',
        'title' => 'Роадмап сервера 0.8.2',
        'description' => 'От живого ангара до открытых дверей сервера. Идёт последняя неделя: бой замкнут полным циклом, живой прогон пройден на 120 клиентах, и до 30 августа остались переезд базы и сборка клиента.',
        'updated' => 'План: 15 июля – 30 августа 2026',
        'progress_label' => 'Общий прогресс',
        'progress_note' => '5 из 6 этапов завершено',
        'progress_value' => 88,
        'current_id' => 'launch',
        'next_id' => 'launch',
        'goal_id' => 'launch',
        'current_label' => 'Текущий фокус',
        'next_label' => 'Далее по плану',
        'details_label' => 'Результат этапа',
        'open_label' => 'Открыть полный роадмап',
        'all_stages_label' => 'Все этапы',
        'timeline_label' => 'Спринт до запуска',
        'timeline_title' => 'Полтора месяца до открытых дверей',
        'timeline_description' => 'Каждый этап заканчивается результатом, который можно проверить в клиенте или на сервере. Порядок этапов переставлен по факту разработки: сначала танк поехал и выстрелил, потом за него взялись экипаж и награда, а отдельный dbmgr, магазин и дерево исследований уехали за дату открытия.',
        'summary' => [
            ['value' => '238', 'label' => 'коммита сервера'],
            ['value' => '30.08', 'label' => 'дата запуска'],
            ['value' => '253', 'label' => 'танка уже в ангаре'],
            ['value' => '120', 'label' => 'игроков в живом прогоне'],
        ],
        'statuses' => [
            'done' => 'Завершено',
            'current' => 'В работе',
            'planned' => 'Запланировано',
            'goal' => 'Запуск',
        ],
        'phases' => [
            [
                'id' => 'start',
                'number' => '00',
                'period' => '15–18 июля 2026',
                'phase' => 'Стартовый спринт',
                'title' => 'С нуля до живого ангара',
                'lead' => 'За 3,5 дня и 122 коммита собран базовый серверный контур и полный путь входа игрока в 3D-ангар.',
                'status' => 'done',
                'meta' => ['3,5 дня', '122 коммита'],
                'tasks' => [
                    'Протокол BigWorld/Mercury с нуля: UDP-фрейминг, reliable-слой (seq/ack), фрагменты, RSA-логин, Blowfish-шифрование канала и внутренний RPC между процессами.',
                    'Полный login-хендшейк → baseapp → сущность Account → showGUI/showLobby → 3D-ангар.',
                    'Все 253 танка игры в карусели: compactDescr из игровых XML, цены магазина, стриминг инвентаря и heartbeat против разрыва сессии.',
                    'Авторизация через БД: логин и пароль сверяются с accounts (sha256, как на сайте), а валюта, имя, премиум и клан поступают из MySQL.',
                ],
            ],
            [
                'id' => 'week-1',
                'number' => '01',
                'period' => '19–26 июля',
                'phase' => 'Неделя 1',
                'title' => 'Личный гараж и первый бой',
                'lead' => 'Ангар стал личным — а на третий день недели танк впервые выехал на арену, на две недели раньше плана.',
                'status' => 'done',
                'meta' => ['8 дней', '36 коммитов'],
                'tasks' => [
                    'Экипаж и модули танков приходят из БД: в ангаре стоит реальная комплектация, а не дефолтная.',
                    'В карусели — танки конкретного аккаунта: настоящие slots, berths и раскладка снаряжения.',
                    'Оборудование и боекомплект: досылатели, вентиляция, оптика и снаряды всех типов покупаются и сохраняются в БД.',
                    'Живой счётчик онлайна с обновлением каждые 15 секунд.',
                    '21 июля — первый бой: вход на арену, сущность Avatar, спавн танка и карта «Малиновка».',
                    'Движение стало серверным: forcedPosition, рельеф, коллизии и плавная физика вместо клиентской отсебятины.',
                    'Выделенный dbmgr и миграцию 2520 аккаунтов осознанно перенесли на этап экономики — сначала закрываем бой.',
                ],
            ],
            [
                'id' => 'week-2',
                'number' => '02',
                'period' => '27 июля – 3 августа',
                'phase' => 'Неделя 2',
                'title' => 'Бой обретает вес',
                'lead' => 'Этап завершён: стрельба, пробитие и разрушения собрались в полноценный бой, очередь и балансировщик ведут игрока на арену, а сервер научился обновлять код без перезапуска.',
                'status' => 'done',
                'meta' => ['8 дней', '13 коммитов'],
                'tasks' => [
                    'Стрельба с перезарядкой и очередью выстрелов, стандартный режим прицела.',
                    'Наведение башни и орудия синхронно с сервером.',
                    'Очередь перед боем и балансировщик: окно ожидания с таймером и составом очереди по уровням и классам.',
                    'Один режим — одна база: встречный бой и маска видимости объектов карты вместо баз всех режимов сразу.',
                    'Модель пробития и повреждений: броня, углы, тип снаряда, попадания по модулям; криты модулей — гусеница сбивается, боеукладка детонирует.',
                    'Разрушаемое окружение: ломаются деревья, строения и прочные заборы, эффекты попадания по своему танку.',
                    'Мультиплеер: несколько танков на одной арене, снаряды не пролетают сквозь чужие корпуса, вражеские танки видны в табах обоих клиентов, стрельба на разных высотах.',
                    'Загружается любая карта, а не только «Малиновка».',
                    'Горячая перезагрузка кода сервера без перезапуска; 4-й антимонолитный проход — монолит разрезан на 9 модулей.',
                ],
            ],
            [
                'id' => 'week-3',
                'number' => '03',
                'period' => '4–17 августа',
                'phase' => 'Недели 3–4',
                'title' => 'Разведка, конец раунда и тик на 100+',
                'lead' => 'Долг по данным снова отложили: окно ушло на то, чтобы бой стал честным — засвет, кусты, конец раунда — и чтобы тик не рассыпался на сотне игроков.',
                'status' => 'done',
                'meta' => ['14 дней', '23 коммита'],
                'tasks' => [
                    'Засвет: врага видно только пока его действительно видят; кусты маскируют, оптика и обзор башни измерены по клиенту.',
                    'Конец раунда, маска баз десятичным текстом, просвет и общие разрушения; переезд через обломки держит весь профиль высоты.',
                    'Криты ломают именно то, во что попали — луч против треугольников вместо зон.',
                    'Отсчёт перед боем, чистый выход в ангар, пушка, которая сама заряжается, круг разброса и форма рассеивания.',
                    'Тик держит 100+ игроков, трупы остаются на поле; метку времени кадра двигает setGameTime — найдено вскрытием exe.',
                    'Сервер слушает клиентов и на localhost, и на внешнем адресе.',
                ],
            ],
            [
                'id' => 'battle',
                'number' => '04',
                'period' => '18–24 августа',
                'phase' => 'Предзапусковая неделя',
                'title' => 'В БОЙ — экипаж, награда и свой res',
                'lead' => 'Бой замкнут: подвеска держит корпус, у экипажа есть перки, за бой платят в кошелёк, а сервер везёт собственный res и больше не надстройка над установленной игрой.',
                'status' => 'done',
                'meta' => ['7 дней', '30 коммитов'],
                'tasks' => [
                    'Корпус лежит на гусеницах: пятно контакта — отрезок, корпус ложится на его плоскость, спуск не пилит, яма не глотает танк.',
                    'Наезд ломает всё — забор падает от касания; танк больше не лезет этажами в разрушенные дома, заезд на холмы Химмельсдорфа.',
                    'Эффективные ТТХ: оборудование, перки и криты реально меняют характеристики машины.',
                    'Перки и пересадка экипажа, окно итогов боя, награда за бой попадает в кошелёк игрока.',
                    'Аудит персистентности: перки, оборудование и модули действительно ложатся в базу.',
                    'Командный чат в бою, сплошные танки и таран; сняты два краша клиента — на старте боя и в конце раунда.',
                    'Собственный res сервера (70,8 МиБ извлечено из клиента) и redirect_config под заданный IP.',
                ],
            ],
            [
                'id' => 'launch',
                'number' => '05',
                'period' => '25–30 августа',
                'phase' => 'Запуск',
                'title' => '30 августа — двери открыты',
                'lead' => 'Последняя неделя уже идёт. Стресс-прогон пройден на 120 живых клиентах, очередь и шарды на месте — остались переезд базы, сборка клиента и дежурство.',
                'status' => 'goal',
                'meta' => ['6 дней', '30 августа'],
                'tasks' => [
                    'Пройдено: живой сквозной прогон — 120 игроков, 3 шарда, 6 арен. Посадка в бой p50 0,70 с · p95 1,17 с, 120 из 120 в бою, тик езды 33,6–33,8 мс против цели 33,3.',
                    'Пройдено: очередь без ожидания и N шардов baseapp — волна уходит досрочно, подсадка в уже идущий бой; ACK склеены, 137 → 68 надёжных пакетов/с.',
                    'Пройдено: вертикаль физики переписана с нуля (корпус на десяти рессорах), в ротации Прохоровка и Хребет Дракона, респаун — от своей базы команды.',
                    'Осталось: перенос 2520 аккаунтов сайта в боевую базу и сверка балансов перед первым днём.',
                    'Осталось: сборка клиента и лаунчер на странице загрузки — один архив, один запуск, без ручных правок конфигов.',
                    'Осталось: мониторинг и дежурство — логи, метрики онлайна и быстрый откат обновления без остановки сервера.',
                    'За дату открытия перенесено: отдельный dbmgr, покупка танков в магазине и дерево исследований.',
                    '30 августа 2026 — сервер открыт для всех: регистрация, ангар и бой доступны без приглашений.',
                ],
            ],
        ],
    ];
}

function orion_roadmap_phase($roadmap, $id) {
    foreach ($roadmap['phases'] as $phase) {
        if ($phase['id'] === $id) {
            return $phase;
        }
    }
    return null;
}
