<?php

function orion_default_updates() {
    return [
        [
            'version' => '1.0',
            'name' => 'Новые Горизонты',
            'date' => '2026-06-21',
            'tag' => 'Крупное обновление',
            'intro' => 'Большое обновление: социальные функции (взводы, друзья, глобальный и локальный чат), новая карта Lakeville, ряд исправлений боевых механик и серьёзная оптимизация сервера под высокий онлайн.',
            'categories' => [
                [
                    'icon' => '💬',
                    'title' => 'Социальные функции',
                    'items' => [
                        ['Взводы', 'объединяйтесь с друзьями в взвод и отправляйтесь в бой вместе.'],
                        ['Глобальный чат', 'общий чат для всех игроков на сервере.'],
                        ['Локальный чат', 'отдельный чат внутри боя.'],
                        ['Друзья', 'добавляйте и удаляйте игроков из списка друзей.'],
                        ['Взводы без премиума', 'снято требование премиум-аккаунта — взвод доступен всем.'],
                    ],
                ],
                [
                    'icon' => '🗺️',
                    'title' => 'Карты',
                    'items' => [
                        ['Новая карта — Lakeville', 'добавлена в ротацию боёв.'],
                        ['Himmelsdorf', 'исправлена коллизия моделей объектов (застревания и наезды).'],
                        ['Направление спавна', 'на Himmelsdorf и Прохоровке танки появляются развёрнутыми в правильную сторону.'],
                    ],
                ],
                [
                    'icon' => '🔧',
                    'title' => 'Техника и модули',
                    'items' => [
                        ['Модули техники', 'добавлены модули для танков (орудия, башни, двигатели, ходовая, рации).'],
                    ],
                ],
                [
                    'icon' => '⚔️',
                    'title' => 'Бой и механики',
                    'items' => [
                        ['Башни других игроков', 'теперь отображается реальный поворот башни союзника или противника, а не следование за вашей камерой.'],
                        ['Снаряды для всех танков', 'догружены боеприпасы — ошибка «снаряды не найдены» на части техники устранена.'],
                        ['Ничья по таймеру', 'если за 15 минут ни одна команда не уничтожена полностью, бой завершается ничьёй.'],
                        ['Утопление', 'танк, полностью находящийся под водой дольше 5 секунд, выводится из строя.'],
                        ['Класс техники в очереди', 'исправлено отображение тяжёлых танков как лёгких.'],
                    ],
                ],
                [
                    'icon' => '🛠️',
                    'title' => 'Сервер и оптимизация',
                    'items' => [
                        ['Оптимизация базы данных', 'дефолтный инвентарь (экипаж, расходники, оборудование) генерируется на лету, в базе хранятся только изменения — меньше занимаемого места, быстрее вход в игру.'],
                        ['Высокий онлайн', 'сервер переведён на многопроцессный кластер с привязкой к ядрам; устранены разрывы у игроков на WARP/zapret. Стабильно держит 100+ игроков одновременно.'],
                    ],
                ],
            ],
        ],
    ];
}

function ensure_update_history_schema($pdo) {
    $pdo->exec("CREATE TABLE IF NOT EXISTS site_updates (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        version VARCHAR(32) NOT NULL,
        name VARCHAR(180) NOT NULL,
        release_date DATE NOT NULL,
        tag VARCHAR(80) NOT NULL DEFAULT '',
        intro TEXT NOT NULL,
        categories_json TEXT NOT NULL,
        status VARCHAR(16) NOT NULL DEFAULT 'draft',
        author_account_id BIGINT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)
    )");
    $pdo->exec("CREATE INDEX IF NOT EXISTS idx_site_updates_public ON site_updates (status, release_date)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS idx_site_updates_author ON site_updates (author_account_id)");
    $pdo->exec("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_site_updates_updated_at') THEN CREATE TRIGGER trg_site_updates_updated_at BEFORE UPDATE ON site_updates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column(); END IF; END $$");

    $seeded = $pdo->prepare("SELECT setting_value FROM site_settings WHERE setting_key = 'update_history_seeded' LIMIT 1");
    $seeded->execute();
    if ($seeded->fetchColumn() !== false) {
        return;
    }

    $count = intval($pdo->query("SELECT COUNT(*) FROM site_updates")->fetchColumn());
    if ($count === 0) {
        $insert = $pdo->prepare("INSERT INTO site_updates (version, name, release_date, tag, intro, categories_json, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, 'published', NOW(), NOW())");
        foreach (orion_default_updates() as $update) {
            $insert->execute([
                $update['version'],
                $update['name'],
                $update['date'],
                $update['tag'],
                $update['intro'],
                json_encode($update['categories'], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
            ]);
        }
    }
    $pdo->exec("INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('update_history_seeded', '1', NOW()) ON CONFLICT (setting_key) DO UPDATE SET setting_value = '1', updated_at = NOW()");
}

function orion_update_categories_from_text($text) {
    $lines = preg_split('/\r\n|\r|\n/', trim((string)$text));
    $categories = [];
    $current = -1;

    foreach ($lines as $line) {
        $line = trim($line);
        if ($line === '') {
            continue;
        }
        if (str_starts_with($line, '##')) {
            $heading = trim(substr($line, 2));
            if ($heading === '') {
                continue;
            }
            $parts = preg_split('/\s+/', $heading, 2);
            $icon = count($parts) > 1 ? $parts[0] : '•';
            $title = count($parts) > 1 ? $parts[1] : $parts[0];
            $categories[] = ['icon' => $icon, 'title' => $title, 'items' => []];
            $current = count($categories) - 1;
            continue;
        }

        $item = array_map('trim', explode('|', $line, 2));
        if (count($item) !== 2 || $item[0] === '' || $item[1] === '') {
            throw new RuntimeException('Каждый пункт обновления должен иметь формат «Заголовок | Описание».');
        }
        if ($current < 0) {
            $categories[] = ['icon' => '•', 'title' => 'Изменения', 'items' => []];
            $current = 0;
        }
        $categories[$current]['items'][] = [$item[0], $item[1]];
    }

    $categories = array_values(array_filter($categories, function ($category) {
        return !empty($category['items']);
    }));
    if (empty($categories)) {
        throw new RuntimeException('Добавьте хотя бы одну категорию и один пункт обновления.');
    }
    return $categories;
}

function orion_update_categories_to_text($categories) {
    $blocks = [];
    foreach ((array)$categories as $category) {
        $lines = ['## ' . trim((string)($category['icon'] ?? '•')) . ' ' . trim((string)($category['title'] ?? 'Изменения'))];
        foreach ((array)($category['items'] ?? []) as $item) {
            $lines[] = trim((string)($item[0] ?? '')) . ' | ' . trim((string)($item[1] ?? ''));
        }
        $blocks[] = implode("\n", $lines);
    }
    return implode("\n\n", $blocks);
}

function orion_update_history($pdo, $include_drafts = false) {
    $where = $include_drafts ? '' : "WHERE status = 'published'";
    $rows = $pdo->query("SELECT * FROM site_updates $where ORDER BY release_date DESC, id DESC")->fetchAll();
    $updates = [];
    foreach ($rows as $row) {
        $categories = json_decode((string)$row['categories_json'], true);
        if (!is_array($categories)) {
            $categories = [];
        }
        $row['date'] = $row['release_date'];
        $row['categories'] = $categories;
        $updates[] = $row;
    }
    return $updates;
}
